### ISSUE TITLE
terraform-docs indent arg usage

### ISSUE THREAD

**Issue by siddmoitra** [antonbabenko/pre-commit-terraform#110]
Hi,
First and foremost, this is working absolutely great for us. So thank you for creating the TF hooks.

Really need some help here with `terraform_docs` hook. I would like to use the [indent flag](https://github.com/segmentio/terraform-docs/blob/master/docs/formats/markdown.md#options) when generating the docs. I tried using 
```
...
- id: terraform_docs
   args: ['--indent=3']
...
```

However it seems not correct as I get an error that the option is not recognized. I am sure there is a way, I am just not so good with bash. Some help here would be greatly appreciated.

**Comment by antonbabenko** [comment]
Hi @siddmoitra !

You should write it like this, for example:
```
    - id: terraform_docs
      args: ['--args=--indent 3 --no-requirements']
```

**Comment by siddmoitra** [comment]
Thank you. 👍
