### ISSUE TITLE
Feature: Sort Variables 

### ISSUE THREAD

**Issue by sblack4** [antonbabenko/pre-commit-terraform#111]
My friends and I have been trying to standardize our terraform modules. One of the things we've started to do is sorting everything, particularly variables, alphabetically. I think this would make a great pre-commit hook.

There's a feature request out there for it https://github.com/hashicorp/terraform/issues/12959 and I've got a script to do this I stole from that thread. I've never written my own pre-commit hook but I'd love to take on something simple like this to get a better idea of how the pre-commit hooks work

**Comment by MaxymVlasov** [comment]
Hi @sblack4 
You can start from [CONTRIBUTING.md](https://github.com/antonbabenko/pre-commit-terraform/blob/master/.github/CONTRIBUTING.md) guide and check the [pre-commit.com](https://pre-commit.com) website.


Feel free to ask any questions - it also helps me write a better contribution doc (#216)
