### ISSUE TITLE
ignore certain modules not pinned to version

### ISSUE THREAD

**Issue by bondezbond** [antonbabenko/pre-commit-terraform#112]
Is it possible to ignore certain modules not pinned to a release version. For example. I have a data only module for tags and I don't want to pin it so if tag standards change. The next deployment will pick up the latest changes from tags without a code commit.

There are other modules in the same terraform project but I want them to be version specific cause they are actual resources. I thought ignore-module would work but that doesn't seem to do it.

**Comment by MaxymVlasov** [comment]
Hi @bondezbond 
1. Do you found an answer to this question anywhere?
2. If not - can you describe more details and how it related to the pre-commit-terraform repo, please?

As I understand, you just need to not specify a module version

```hcl
source = git::https://github.com/ORG/REPO.git
# or
source = git::https://github.com/ORG/REPO.git?ref=main_branch
```

**Comment by bondezbond** [comment]
we can close this. This is more of an issue with tflint. With `flexible` style `source = git::https://github.com/ORG/REPO.git` you would get this error so that doesn't work. 

The only workaround is to do another non-default tag that's always pointing to latest commit.
