### ISSUE TITLE
Check version of terraform-docs or tflint 

### ISSUE THREAD

**Issue by aschepp** [antonbabenko/pre-commit-terraform#115]
It would be nice to have an option to require certain versions of terraform-docs or tflint to prevent that users are using older/newer versions and creating different README.md files for example.

**Comment by MaxymVlasov** [comment]
Related to https://github.com/antonbabenko/pre-commit-terraform/issues/69

**Comment by MaxymVlasov** [comment]
Hi.
You can use [`Docker` installation](https://github.com/antonbabenko/pre-commit-terraform#1-install-dependencies) for now.


Closed as a duplicated of #188
