### ISSUE TITLE
Misprint in tflint args example

### ISSUE THREAD

**Issue by volk1234** [antonbabenko/pre-commit-terraform#119]
There are 2 examples of using `args` in `Notes about terraform_tflint hooks` chapter:
```
hooks:
  - id: terraform_tflint
    args: ['args=--deep']
```
This not works with **tflint** inside pre-commit hook. Clean tflint with the parameters work for me. 

 As far as I can see from the hook's bash script this should be with two minuses before internal `args` parameter, e.g.
```
hooks:
  - id: terraform_tflint
    args: ['--args=--deep']
```
This one works for me.
 So it looks like it not and issue in the code but the wrong documented parameter.

**Comment by antonbabenko** [comment]
This has been fixed in #125 

[v1.33.0](https://github.com/antonbabenko/pre-commit-terraform/releases/v1.33.0) has been just released.
