### ISSUE TITLE
Is there an equivalent tool for building the README.md for a provider written in Go?

### ISSUE THREAD

**Issue by rquadling** [antonbabenko/pre-commit-terraform#131]
Really like pre-commit-terraform. Nice and easy and all the fail left you could desire.

Looking to be able to use a provider (https://github.com/Mastercard/terraform-provider-restapi) but it needs some small amount of work for getting it into the registry.

One part is the documentation. And so, considering how good pre-commit-terraform gets things done via `terraform-docs` for terraform scripts, I was wondering if there is an equivalent tool for working on a terraform provider written in Go.

I'm not a Go developer, so that's why I'm looking for some automation on this.

**Comment by MaxymVlasov** [comment]
Hi @rquadling 
Please, share your solution with us.

Also, https://github.com/terraform-docs/terraform-docs is written in Go, so, I think, it can be used natively or with a small wrapper.

**Comment by MaxymVlasov** [comment]
If you will read this, be sure that we'd like to know your solution.

Close issue as stale and does not yet need work on our part

**Comment by rquadling** [comment]
I'm not the author of the tool, but it was the lack of documentation that is one of the factors holding it back.

**Comment by antonbabenko** [comment]
There is also https://github.com/bflad/tfproviderdocs which is "A documentation tool for Terraform Provider code". Sounds like this is what you are looking for but I am not sure how stable it is.

In most cases, the documentation for Terraform providers is written manually by the developers.
