### ISSUE TITLE
brew install pre-commit upgrades python to python3.8

### ISSUE THREAD

**Issue by saurabh-hirani** [antonbabenko/pre-commit-terraform#133]
The documentation mentions to install pre-commit on MacOS via `brew install pre-commit`

As per https://formulae.brew.sh/formula/pre-commit pre-commit depends on python3.8 and this would upgrade a user's python setup also. This is an unintended side effect. It would help to update the docs to call out to install pre-commit via pip - `pip install pre-commit` to keep python version same.

**Comment by acdha** [comment]
This seems like the desired behaviour for most users. If you have a project which doesn't support Python 3.8, you can back-level just that project by running `brew install python@3.7` and using that until the code can be updated.

**Comment by antonbabenko** [comment]
Installing pre-commit is well covered in the official documentation. I don't think we need to duplicate it here in more detail.

Use whatever you have available on your setup - brew, pip, pip3, etc...

Closing this issue.
