### ISSUE TITLE
default config of terraform_docs fails

### ISSUE THREAD

**Issue by rgevaert** [antonbabenko/pre-commit-terraform#148]
Hi,

terraform-docs has removed the --aggregate-type-defaults flag with the latest release.

https://github.com/terraform-docs/terraform-docs/blob/38316ec246f3eea4ed737f7d8bf54f2faabd6ff2/CHANGELOG.md#v080---2020-01-17

terraform_docs_without_aggregate_type_defaults hook still works. But terraform_docs doesn't anymore because of this.

**Comment by antonbabenko** [comment]
Thanks for opening this issue!

What do you think if have both `terraform_docs_without_aggregate_type_defaults` and `terraform_docs` acting identically (for backward compatibility reasons)?

/cc @robinbowes @rgevaert

**Comment by rgevaert** [comment]
I am fine with that. 

Also maybe #57 is linked to this? In any case it can be closed if this one is closed I think. As I "tested" it.

**Comment by antonbabenko** [comment]
[v1.41.0](https://github.com/antonbabenko/pre-commit-terraform/releases/v1.41.0) has been just released.

**Comment by acdha** [comment]
Awesome, thank you!
