### ISSUE TITLE
Add a way to fix versions

### ISSUE THREAD

**Issue by sblask** [antonbabenko/pre-commit-terraform#153]
I just ran into a problem with different versions of terraform-docs being used on my machine and on CI. It would be great to have a way to specify compatible versions and throwing an error if the version is not installed. Even better of course would be if pre-commit-terraform would handle versions and I wouldn't have to install terraform-docs(and others) myself.

**Comment by khos2ow** [comment]
This is quite similar to what I mentioned in https://github.com/antonbabenko/pre-commit-terraform/issues/188#issuecomment-857988611.

**Comment by MaxymVlasov** [comment]
Hi. 
At least for now, you can use the [docker image](https://github.com/antonbabenko/pre-commit-terraform/pull/219), which will be merged in few days (I suppose).

Closed as a duplicated of #188
