### ISSUE TITLE
terraform-validate fails if modules are not initialized

### ISSUE THREAD

**Issue by ahmad-hamade** [antonbabenko/pre-commit-terraform#157]
The hook `terraform-validate` will fail if the terraform modules are not initialized with `terraform init -backend=false`.

Any reason for not adding this missing step as part of the validation hook script like in `gruntwork-io/pre-commit` hooks?

https://github.com/gruntwork-io/pre-commit/blob/master/hooks/terraform-validate.sh#L12

**Comment by antonbabenko** [comment]
I was working a bit on it during week-ends. #158 is almost complete.

**Comment by ahmad-hamade** [comment]
Thank you @antonbabenko 😃

**Comment by antonbabenko** [comment]
Please give a try to [v1.44.0](https://github.com/antonbabenko/pre-commit-terraform/releases/tag/v1.44.0).

**Comment by ahmad-hamade** [comment]
I've tested and it works perfectly.

Thanks a lot, @antonbabenko 👍
