### ISSUE TITLE
Terraform validate does not initialize in other directories (examples)

### ISSUE THREAD

**Issue by krathow** [antonbabenko/pre-commit-terraform#160]
Hey,

we're using the terraform_validate hook.
Great that does an init now to not fail anymore.
Would be amazing to do this also in directories that call that module.

My Use-Case:
example-directory showing the execution of the module.
A terraform init in that directory would also be necessary for us.

Proposal: add an argument for terraform_validate to add directories for also executing the init.

**Comment by antonbabenko** [comment]
I agree that the possibility to exclude directories where init and/or validate should run would be helpful. I don't think I will work on this myself, but I will be very glad to review a PR if anyone wants to make it.

**Comment by krathow** [comment]
Hey,

just reviewed it, with #158 it works fine for me, seems I was running v1.43.0.

Thanks for your help and this great repo!
