### ISSUE TITLE
tflint failing with no errors and exit-code 3

### ISSUE THREAD

**Issue by TidBitCo** [antonbabenko/pre-commit-terraform#178]
![image](https://user-images.githubusercontent.com/79685283/109459589-0efdd300-7a9a-11eb-9ce0-acac600c48a7.png)

I am using ubuntu on windows and there are no errors but the hook still fails only for tflint.

**Comment by antonbabenko** [comment]
Hi!,

You can run `pre-commit run -a --version terraform_tflint` to see some more output.

Maybe this issue is related - https://github.com/terraform-linters/tflint/issues/528

I am rather sure this issue is related to the behavior of `tflint` tool so closing it.
