### ISSUE TITLE
failing hook leaves temp files in repo root

### ISSUE THREAD

**Issue by brandoconnor** [antonbabenko/pre-commit-terraform#18]
If temp files need to be a part of this hook, I'd suggest putting them in a standard tucked away temp file location on the system. Since you're using bash anyway, we can assume Windows isn't supported unless through WSL. Consider sticking temp files in `/tmp/` and having some cleanup logic if the hook fails.

<img width="817" alt="screen shot 2018-05-17 at 12 48 57 am" src="https://user-images.githubusercontent.com/2502520/40274689-04dd6342-5b92-11e8-9dd8-eb3b51bbb07b.png">

**Comment by antonbabenko** [comment]
This has been resolved by #16
