### ISSUE TITLE
.precommit-config-yaml required in each module (subfolder)?

### ISSUE THREAD

**Issue by varun1231** [antonbabenko/pre-commit-terraform#187]
I have a Terraform repository and have folders for modules. Why do I have to have .precommit-config-yaml under each folder when I have .precommit-config-yaml at the root of the repository. When I try to commit my changes, I get the following error on my mac.

No {dir}/.pre-commit-config.yaml file was found
- To temporarily silence this, run `PRE_COMMIT_ALLOW_NO_CONFIG=1 git ...`
- To permanently silence this, install pre-commit with the --allow-missing-config option
- To uninstall pre-commit run `pre-commit uninstall`

Manual run of pre-commit against all the files using `pre-commit run -a` works fine.

**Comment by antonbabenko** [comment]
Normally, you have one file `.pre-commit-config.yaml` in the root of your git repository. Only this file will be used when you run `git commit` or `pre-commit run -a`

Please read much more detailed instructions on the official site - https://pre-commit.com/

**Comment by varun1231** [comment]
@antonbabenko I have read the instructions and it does say that there is one `.pre-commit-config.yaml` required in the root of the directory. Though, when I don't have a separate `.pre-commit-config.yaml` file under a folder/module in the repository, it gives me the above error while committing the code..

**Comment by antonbabenko** [comment]
Not sure I understand.

`.pre-commit-config.yaml` is required to be at the root of your git repo. If there is no such file, there will be an error you see.

**Comment by varun1231** [comment]
I have `.pre-commit-config.yaml` at the root of the git repo. That's not enough - I am required to have a pre-commit at the root of each folder in the git repo (there are no .tf files in the root of the git repo; only folders exist which have terraform config). When I don't have `.pre-commit-config.yaml` in each folder and try to commit the changes in that folder - that's when I see this error!
