### ISSUE TITLE
terraform_validate_no_variables fails if there is no .tf files

### ISSUE THREAD

**Issue by robinbowes** [antonbabenko/pre-commit-terraform#19]
I've got a terragrunt config tree like this:

```
live
├── aws
│   ├── aws
│   │   ├── cloud.tfvars
│   │   ├── eu-west-1
│   │   │   ├── development
│   │   │   │   └── terraform.tfvars
│   │   │   ├── production
│   │   │   │   └── terraform.tfvars
│   │   │   ├── region.tfvars
│   │   │   └── staging
│   │   │       └── terraform.tfvars
│   │   └── us-east-1
│   │       └── development
│   └── site.tfvars
└── terraform.tfvars
```

I have the `terraform_validate_no_variables` pre-commit hook enabled and it fails with the following msg:

```
Error: No Terraform configuration files found in directory:
```

**Comment by antonbabenko** [comment]
Looks like a bug. It should verify that there are `*.tf` files between line 17 and 18: https://github.com/antonbabenko/pre-commit-terraform/blob/2d3782cefadb0941102fe413ab08a75905fcd081/terraform_validate_no_variables.sh#L17-L18

**Comment by robinbowes** [comment]
Gotta love open source.
