### ISSUE TITLE
pre-commit not running in sub folders

### ISSUE THREAD

**Issue by travis-jorge** [antonbabenko/pre-commit-terraform#190]
When I run pre-commit run -a I always get
```
Terraform fmt........................................(no files to check)Skipped 
Terraform validate...................................(no files to check)Skipped
Terraform docs.......................................(no files to check)Skipped
```

the project format is 
root 
->.terraform
->main.tf
ect...

I also tried pre-commit run --files .terraform/* 
and i get the same. How do i configure pre-commit to run in the .terraform folder?

**Comment by antonbabenko** [comment]
Files inside `.terraform` are excluded (see [the config](https://github.com/antonbabenko/pre-commit-terraform/blob/master/.pre-commit-hooks.yaml#L7)), and this is the right behavior.

You should think about `.terraform` folder as a cache folder used solely by the Terraform internally, and you should apply pre-commit to your `*.tf` files.

**Comment by travis-jorge** [comment]
ah ok, i was beginning to think that was the case. I got handed this file structure I will discuss with the team about changing it. Thank you for the help!
