### ISSUE TITLE
[terraform_docs] Enable target different file instead of README.md

### ISSUE THREAD

**Issue by nicholastcs** [antonbabenko/pre-commit-terraform#215]
Hi, 

I wanted to ask that if it is possible to have custom markdown file (e.g. `docs.md` or `readme.md`) for `terraform_docs` instead of using the default `README.md`?

Perhaps it is available to pass in the args in the `.pre-commit-config.yaml`?

Thanks.

**Comment by MaxymVlasov** [comment]
Hi @nicholastcs, it is not yet possible
https://github.com/antonbabenko/pre-commit-terraform/blob/master/terraform_docs.sh#L113


It will be done in #7, close as duplicated
