### ISSUE TITLE
Docker Image doesn't get compiled

### ISSUE THREAD

**Issue by ivankorn** [antonbabenko/pre-commit-terraform#217]
```
Archive:  tflint.zip
  inflating: tflint
curl: (3) <url> malformed
The command '/bin/sh -c add-apt-repository ppa:deadsnakes/ppa &&     apt install -y python3.7 python3-pip &&     pip3 install pre-commit==${PRE_COMMIT_VERSION} &&     curl -L "$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases | grep -o -E "https://.+?${TERRAFORM_DOCS_VERSION}-linux-amd64.tar.gz")" > terraform-docs.tgz && tar xzf terraform-docs.tgz && chmod +x terraform-docs && mv terraform-docs /usr/bin/ &&     curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases | grep -o -E "https://.+?/${TFLINT_VERSION}/tflint_linux_amd64.zip")" > tflint.zip && unzip tflint.zip && rm tflint.zip && mv tflint /usr/bin/ &&     curl -L "$(curl -s https://api.github.com/repos/tfsec/tfsec/releases | grep -o -E "https://.+?/${TFSEC_VERSION}/tfsec-linux-amd64")" > tfsec && chmod +x tfsec && mv tfsec /usr/bin/ &&     python3.7 -m pip install -U checkov==${CHECKOV_VERSION}' returned a non-zero code: 3
✘-3 ~/Soft/no-rpms/pre-commit-terraform [master|✔]
~                                                     
```

The command

``` '/bin/sh -c add-apt-repository ppa:deadsnakes/ppa &&     apt install -y python3.7 python3-pip &&     pip3 install pre-commit==${PRE_COMMIT_VERSION} &&     curl -L "$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases | grep -o -E "https://.+?${TERRAFORM_DOCS_VERSION}-linux-amd64.tar.gz")" > terraform-docs.tgz && tar xzf terraform-docs.tgz && chmod +x terraform-docs && mv terraform-docs /usr/bin/ &&     curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases | grep -o -E "https://.+?/${TFLINT_VERSION}/tflint_linux_amd64.zip")" > tflint.zip && unzip tflint.zip && rm tflint.zip && mv tflint /usr/bin/ &&     curl -L "$(curl -s https://api.github.com/repos/tfsec/tfsec/releases | grep -o -E "https://.+?/${TFSEC_VERSION}/tfsec-linux-amd64")" > tfsec && chmod +x tfsec && mv tfsec /usr/bin/ &&     python3.7 -m pip install -U checkov==${CHECKOV_VERSION}' ``` returned a non-zero code: 3

steps to reproduce:
1)  `git clone git@github.com:antonbabenko/pre-commit-terraform.git`
2)  `cd pre-commit-terraform`
2) `docker build -t pre-commit .`

**Comment by MaxymVlasov** [comment]
@mavogel can you please describe how to use dockerized `pre-commit-terraform`? Where code should be mounted and so on.

@ivankorn Can you please check that changes in `GH-217/fix_docker` works for you?
Also, if you can provide the command that you use to check the code - I would be very grateful.
