### ISSUE TITLE
terraform_validate hooks don't exit with non-zero status, never report failure

### ISSUE THREAD

**Issue by tklovett** [antonbabenko/pre-commit-terraform#22]
From the pre-commit docs for Creating New Hooks:
> The hook must exit nonzero on failure or modify files in the working directory (since 0.6.3).

Neither of the validation hooks in this repo will exit with a non-zero status on failure. The `if ! terraform validate` command uses the non-zero exit code, and then moves on. The scripts will then reach end of file and `exit 0`.

Because they `exit 0`, pre-commit interprets that as Passed and suppresses all output. For my own project, I've enabled the `verbose` option so that its not a no-op.

https://github.com/antonbabenko/pre-commit-terraform/blob/b7c50947b0f3968172a9c5a4df2ad3bb203dca22/terraform_validate_no_variables.sh#L19
https://github.com/antonbabenko/pre-commit-terraform/blob/b7c50947b0f3968172a9c5a4df2ad3bb203dca22/terraform_validate_with_variables.sh#L19

**Comment by tklovett** [comment]
I'd submit a PR for this, but I'll be OOO soon for a couple weeks and won't be able to respond to review comments

**Comment by antonbabenko** [comment]
Hi Thomas,

Thank you for the opening this issue. I am OOO myself for the next month, so I won’t be able to make a proper review also.

Have a great summer!

Best regards,
Anton.

11 лип. 2018 р. о 20:54 Thomas Lovett <notifications@github.com> пише:

**Comment by antonbabenko** [comment]
@tklovett Please send a PR if you have time and possibility.

**Comment by antonbabenko** [comment]
Closing as fixed.
