### ISSUE TITLE
feat: Add argument like `force-init` to do init before terraform validate

### ISSUE THREAD

**Issue by antonbabenko** [antonbabenko/pre-commit-terraform#224]
Add an argument to `terraform_validate` to run `terraform init` before running `terraform validate`.

_Originally posted by @eytanhanig in https://github.com/antonbabenko/pre-commit-terraform/issues/203#issuecomment-918791847_

Notes fo contributors:
* [`--hook-config` support example](https://github.com/antonbabenko/pre-commit-terraform/blob/master/terraform_docs.sh#L32-L46)
* [K/V that passed to `--hook-config` support example](https://github.com/antonbabenko/pre-commit-terraform/blob/master/terraform_docs.sh#L118-L142)

---

Additionally to `force-init` option, we can use `terraform providers` and run `terraform init` if necessary, automatically. See this comment for more details - https://github.com/antonbabenko/pre-commit-terraform/issues/299#issuecomment-992323031

**Comment by MaxymVlasov** [comment]
Not needed anymore. The current realization is superior to that

If there are no deps for `t validate` - it will fail in a fraction of a second, so no need to "force-init"

https://github.com/antonbabenko/pre-commit-terraform/blob/8bcd633aaeaff836ac5cffa3a020c8ab678a6b54/hooks/terraform_validate.sh#L114-L133
