### ISSUE TITLE
terraform validate with / with out variable hooks not working.

### ISSUE THREAD

**Issue by ashrith1357** [antonbabenko/pre-commit-terraform#24]
Hello,

 Frist, thank you so much for the shared pre-commit code. i am referencing this original repo in pre-config yaml but somehow both validation with / without variable ones are not working as expected. see below.

λ cat .pre-commit-config.yaml
```
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.7.3
  hooks:
    - id: terraform_fmt
    - id: terraform_validate_no_variables
    - id: terraform_validate_with_variables
```

λ pre-commit install
pre-commit installed at C:\Cloud\Github\pre-commit\tf-test3\tf-test3\.git\hooks\pre-commit

λ git status
modified:   main.tf

λcat main.tf
```
provider "aws" {}
resource "aws_s3_bucket_test1" "b" "e" "f" {
  bucket1                   = "my-tf-test-bucket-1"
  acl     = "private"
}
provider "aws" {}
resource "aws_s3_bucket_test2" "b" "c" "d" {
  bucket1 = "my-tf-test-bucket-2"
  acl                 = "private-public"
}
```

λ git commit -m "main.tf add"                                                                      
Terraform fmt............................................................Failed                    
hookid: terraform_fmt                                                                              
                                                                                                   
Files were modified by this hook. Additional output:                                               
 main.tf                                                                                            
                                                                                                   
Terraform validate without variables.....................................Passed                    
Terraform validate with variables........................................Passed                    

We can see here that fmt working as expected but somehow validation hooks are not catching the issues in main.tf file ( which shouldn't go through validation passed ).

Really appreciate help on this.

**Comment by antonbabenko** [comment]
There is only one `terraform_validate` hook when using Terraform 0.12 and [v1.15.0](https://github.com/antonbabenko/pre-commit-terraform/releases/v1.15.0) which has been released lately.

Closing this issue.
