### ISSUE TITLE
Merge `terraform_docs_replace` functionality to `terraform_docs`

### ISSUE THREAD

**Issue by MaxymVlasov** [antonbabenko/pre-commit-terraform#248]
### What problem are you facing?

It's mostly the same hooks, that need to be maintained separately.

### How could pre-commit-terraform help solve your problem?

Decrease maintainability flow, like this #177

**Comment by adamantike** [comment]
If this idea is already accepted, can it have a short-term fix to mark `terraform_docs_replace` as deprecated? I started using these hooks last week, and went with `terraform_docs_replace` because of wanting for the Readme to be completely managed by it. However, right now, the shortcomings of going with this hook aren't listed (mainly, unsupported `terraform-docs` flags).

**Comment by sharkymcdongles** [comment]
Can you please document how to use terraform_docs hook to have identical behavior to terraform_docs_replace since it is now deprecated? I couldn't seem to find any documentation on this as you'd expect with a deprecation.

**Comment by sharkymcdongles** [comment]
> Hi, sure we do. But for me, firstly need to understand what the `terraform_docs_replace` hook does. Those plans were postponed during all our team members now at war with Russia, during their full-scale invasion of our homeland, Ukraine. So, it deprecated, but not to be removed until summer, I guess.
> 
> Feel free to send your PR with this doc

I didn't know they were from there. I will try and understand how it works with some testing on my end and submit some docs then. Slava Ukraini!!!

**Comment by MaxymVlasov** [comment]
@carlosjgp I think we can add `.terraform-docs.yml` instructions to README and printing out in `terraform_docs_replace` hook [here](https://github.com/antonbabenko/pre-commit-terraform/blob/07c6764c309d14fd37536e6c679354ab99c59a59/hooks/__init__.py) with link to replacement specified in `https://github.com/antonbabenko/pre-commit-terraform/issues/248#issuecomment-1290829226`

Would you like to make PR?

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.76.1 :tada:
