### ISSUE TITLE
terraform_docs is broken in 1.7.4

### ISSUE THREAD

**Issue by djgoku** [antonbabenko/pre-commit-terraform#26]
Clone this repo: https://github.com/djgoku/pre-commit-terraform-docs-failure

see README.md in master for output for both 1.7.3 vs 1.7.4 version.

**Comment by antonbabenko** [comment]
Thanks for opening this issue, I need to know more details to be able to help - OS, version of `terraform-docs`, version of `bash`, terraform templates you use (maybe there is some edge case).

**Comment by djgoku** [comment]
OS: macOS 10.4.2
terraform-docs: 0.3.0 and 0.5.0
bash: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
terraform: v0.11.10
python: 3.6.6

**Comment by djgoku** [comment]
If you clone the repo it has two branches that you can use as test cases.

**Comment by djgoku** [comment]
This is working now in `v1.8.1`. Closing this issue.

**Comment by antonbabenko** [comment]
This is good, but also strange because there were no changes related to `terraform_docs` hook if we look into diff here - https://github.com/antonbabenko/pre-commit-terraform/compare/v1.7.4...v1.8.1
