### ISSUE TITLE
terraform_validate uses different provider versions causing the validation to fail

### ISSUE THREAD

**Issue by chalmagr** [antonbabenko/pre-commit-terraform#276]
### Describe the bug

The execution of terraform_validate hook ignores provider restrictions from root directory causing provider missmatching when executing the terraform validation preventing to commit code (issue recently surfaced when google's provider version 4 was released)

### How can we reproduce it?

- Create project using the file samples below

    <details>
    <summary>.pre-commit-config.yml</summary>

    ```yaml
    default_stages: [commit]
    repos:
    
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.55.0
      hooks:
      - id: terraform_validate
    ```
    </details>
    <details>
    <summary>providers.tf</summary>
    
    ```tf
    terraform {
      required_providers {
        google = {
          version = "~> 3.65"
        }
        google-beta = {
          version = "~> 3.65"
        }
      }
    }
    ```
    </details>
    
    
    <details>
    <summary>main.tf</summary>
    
    ```tf
    variable "project_id" {}
    variable "key_ring_name" {}
    variable "key_name" {}
    
    module "keys" {
      source = "./modules/keys"
    
      project_id = var.project_id
      key_ring_name = var.key_ring_name
      key_name = var.key_name
    }
    ```
    
    </details>
    
    
    <details>
    <summary>modules/keys/keys.tf</summary>
    
    ```tf
    data "google_kms_key_ring" "key_ring" {
      project  = var.project_id
      name     = var.key_ring_name
      location = var.key_ring_location
    }
    data "google_kms_crypto_key" "key" {
      key_ring = data.google_kms_key_ring.key_ring.self_link
      name     = var.key_name
    }
    variable "project_id" {
      type = string
    }
    variable "key_ring_name" {
      type = string
    }
    variable "key_ring_location" {
      type    = string
      default = "global"
    }
    variable "key_name" {
      type = string
    }
    ```
    
    </details>

- Ensure no .terraform directories exist
```bash
find . -type d -name ".terraform" -exec rm -rf {} \; -prune
```
- Run terraform init && terraform validate - it should succeed

    <details><summary>expected output</summary>
    
    ```bash
    $ terraform init && terraform validate
    Initializing modules...
    - keys in modules/keys
    
    Initializing the backend...
    
    Initializing provider plugins...
    - Checking for available provider plugins...
    - Downloading plugin for provider "google-beta" (hashicorp/google-beta) 3.90.1...
    - Downloading plugin for provider "google" (hashicorp/google) 3.90.1...
    
    Terraform has been successfully initialized!
    
    You may now begin working with Terraform. Try running "terraform plan" to see
    any changes that are required for your infrastructure. All Terraform commands
    should now work.
    
    If you ever set or change modules or backend configuration for Terraform,
    rerun this command to reinitialize your working directory. If you forget, other
    commands will detect it and remind you to do so if necessary.
    Success! The configuration is valid.
    ```
    
    </details>

- Delete .terraform directories again with previous command

- Run pre-commit hooks - error is displayed
    
    <details><summary>error output</summary>
    
    ```bash
    $ pre-commit run -a
    Terraform validate.......................................................Failed
    - hook id: terraform_validate
    - exit code: 1
    
    Validation failed: modules/keys
    
    Error: Unsupported attribute
    
      on keys.tf line 8, in data "google_kms_crypto_key" "key":
       8:   key_ring = data.google_kms_key_ring.key_ring.self_link
    
    This object has no argument, nested block, or exported attribute named
    "self_link".
    ```
    
    </details>

### Environment information

* OS:  Docker on MacOS

* `uname -a` and/or `systeminfo | Select-String "^OS"` output:

```bash
Linux b64f144159f8 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

* Tools availability and versions:

```bash
pre-commit 2.13.0
Terraform v0.12.31
Python 3.8.6
Python 3.8.6
checkov checkov SKIPPED
terraform-docs version v0.10.1 2c91c55 linux/amd64 BuildDate: 2020-09-28T22:18:31+0000
terragrunt SKIPPED
terrascan terrascan SKIPPED
TFLint version 0.22.0
tfsec You are running a locally built version of tfsec.
```

* `.pre-commit-config.yaml`:
    
    <details><summary>file content</summary>

    ```yaml
    default_stages: [commit]
    repos:
    
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.55.0
      hooks:
      - id: terraform_validate
    ```

</details>

**Comment by MaxymVlasov** [comment]
It is because `terraform validate` runs only in the current folder, when `pre-commit run` runs recurcivelly in each folder that has changes. 

In your code exist 2 dirs:
```txt
./
./modules/keys
```

if you checkout to `/modules/keys` and run `terraform validate` you will see the same error as in hook
```bash
$ cd modules/keys

$ t init
<output omitted>

$ t version
Terraform v0.12.31
+ provider.google v4.0.0
<output omitted>

$ t validate

Error: Unsupported attribute

  on keys.tf line 7, in data "google_kms_crypto_key" "key":
   7:   key_ring = data.google_kms_key_ring.key_ring.self_link

This object has no argument, nested block, or exported attribute named
"self_link".
```

**Comment by MaxymVlasov** [comment]
You need to pin the provider's version in the modules to specify at leat minimum supported version. In your case, when your module fails with a new major version, you should also specify the maximum support version.

It's how to terraform works.

**Comment by yermulnik** [comment]
As another use case resolution I'd look into excluding `module/keys` dir from `terraform_validate` hook processing since (if I got the topicstarter right) it's not meant to validate TF code in `module/keys` dir. You can find an example here: https://github.com/antonbabenko/pre-commit-terraform/blob/master/.pre-commit-hooks.yaml#L45-L52
So something like the below should do the thing (@MaxymVlasov please correct me if I made a mistake in the code below or misinterpreted configuration):
```yaml
default_stages: [commit]
repos:

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.55.0
  hooks:
  - id: terraform_validate
    exclude: (\.terraform\/|module\/keys\/).*$
```

**Comment by MaxymVlasov** [comment]
Yeah, exclude for config file exists too
https://pre-commit.com/#pre-commit-configyaml---top-level

**Comment by MaxymVlasov** [comment]
But I think that modules should be able to work separately from restrictions specified in envs.

If this deps is module deps, they should be explicitly specified in module.
```hcl
terraform {
  required_version = ">= 0.12"
  required_providers {
    google = {
      version = "~> 3.0"
    }
    google-beta = {
      version = "~> 3.0"
    }
  }
}
```

And you then can clarify the dependencies on the env like

```hcl
terraform {
  required_version = "~> 0.12.0"
  required_providers {
    google = {
      version = "~> 3.65"
    }
    google-beta = {
      version = "~> 3.65"
    }
  }
}
```

Of course, for mature providers and for not actively maintained modules recommended in modules  to specify only the lowest needed deps version, like below, but maybe it's not your case

```hcl
terraform {
  required_version = ">= 0.12"
  required_providers {
    google = {
      version = ">= 3.0"
    }
    google-beta = {
      version = ">= 3.0"
    }
  }
}
```

**Comment by chalmagr** [comment]
@MaxymVlasov thanks for all the updates, quite insightful (new in the terraform world here)

Have a couple of concerns with some of this items... in the example above there is just one module created for simplicity purposes, but in the real project we have 9 modules which are mostly there for duplicate extraction and allow reusing (i.e. not referenced by any other project) and having to add the required_providers for modules that are part of the same project seems redundant and repetitive. If this were a remote module using git / http / etc, then it would be definitely be required to define such module requirements properly to prevent version clashing between different code bases.

What I am thinking is, if there is a .terraform initialized in a parent directory, then it should use plugins from that directory - I have tried a quick change to test this and will create a PR if this helps ... otherwise this will prevent having a cleaner coding solution where different components / modules could be extracted out and not require to add duplication for provider requirements when not having those kept in a separate repository/location

Do you foresee any issues with something like this?

**Comment by yermulnik** [comment]
> if there is a .terraform initialized in a parent directory, then it should use plugins from that directory

Not sure I'm getting the gist of the comment right, but ain't [Provider Plugin Cache](https://www.terraform.io/docs/cli/config/config-file.html#provider-plugin-cache) is what you're seeking for?
