### ISSUE TITLE
The hook terraform_docs_replace uses sed

### ISSUE THREAD

**Issue by RothAndrew** [antonbabenko/pre-commit-terraform#28]
The `terraform_docs_replace` hook uses `sed`, rather than taking care of the cleaning up of the document using native Python. Removing the dependency on `sed` will make this hook more platform agnostic.

**Comment by antonbabenko** [comment]
Fixed in #176, [v1.47.0](https://github.com/antonbabenko/pre-commit-terraform/releases/v1.47.0) has been just released.
