### ISSUE TITLE
Add GH Actions which will build Dockerfile if updated

### ISSUE THREAD

**Issue by antonbabenko** [antonbabenko/pre-commit-terraform#291]
GH Actions for pull-requests which runs `docker build` when `Dockerfile` changes and run the smoke test?

No need to push it to GHCR but just getting versions should be enough. Similar to this one - https://github.com/antonbabenko/pre-commit-terraform/blob/master/.github/workflows/build-image.yaml

_Originally posted by @antonbabenko in https://github.com/antonbabenko/pre-commit-terraform/issues/288#issuecomment-986849696_

**Comment by mohitsaxenaknoldus** [comment]
Hey, can I work on this?

**Comment by antonbabenko** [comment]
Sure, @mohitsaxenaknoldus !

**Comment by mohitsaxenaknoldus** [comment]
Where can I find the smoke tests?

**Comment by MaxymVlasov** [comment]
If you write them and populate somewhere in `tests/` folder + info how to use them in `.github/CONTRIBUTING.md` it will be helpful.

For now we have only some kind of perfomance tests

**Comment by mohitsaxenaknoldus** [comment]
So I also have to create the smoke tests as well then?

**Comment by MaxymVlasov** [comment]
Yep

**Comment by mohitsaxenaknoldus** [comment]
I've added workflow which will build the Dockerfile if it was changed but I've never worked with smoke tests before :(

**Comment by mohitsaxenaknoldus** [comment]
Here's the work so far: https://github.com/antonbabenko/pre-commit-terraform/pull/318

**Comment by MaxymVlasov** [comment]
Maybe we already have the simplest optimistic smoke test here:
https://github.com/antonbabenko/pre-commit-terraform/blob/c5f2a618a83f04113a3a27475663a709e2c83f5f/Dockerfile#L129-L141

@antonbabenko do you'd like to have pre-commit run on some predefined code for each hook? Or what do you mean by "smoke test"?

**Comment by antonbabenko** [comment]
I think the simplest optimistic smote test you refer to is a pretty accurate definition of what I meant by "smoke test" :)

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.63.0 :tada:
