### ISSUE TITLE
infracost_breakdown.sh: line 119: - 1 Substring Expression < 0

### ISSUE THREAD

**Issue by yobooooi** [antonbabenko/pre-commit-terraform#294]
### Describe the bug
Hi,

I hope you're well. 

I was trying to implement the infracost break down pre-commit, but following the documentation I'm unable to get one of the `hook-configs` to work. I am expecting the hooks to compare against the jq values but I am always getting the following error. I've tried simplifying my pre-commit configs, I can get the break down of the costs but as soon as I try to do any comparisons via the `hook-configs` I will get the error below.

`/Users/adan/.cache/pre-commit/repomv704sf7/infracost_breakdown.sh: line 119: -1: substring expression < 0`

### How can we reproduce it?
Run pre-commit with the following configuration `pre-commit run --all-files`

```bash
pre-commit run --all-files
Check Yaml...............................................................Passed
Check JSON...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
Don't commit to branch...................................................Passed
Terraform validate.......................................................Passed
Infracost breakdown......................................................Passed
- hook id: infracost_breakdown
- duration: 4.21s

/Users/adan/.cache/pre-commit/repomv704sf7
Detected Terraform directory at ./decred/terraform
  ✔ Checking for cached plan... found
Detected Terraform directory at ./doge/terraform
  ✔ Checking for cached plan... found
Detected Terraform directory at ./lnbt/terraform
  ✔ Checking for cached plan... found
Detected Terraform directory at ./ltc/terraform
  ✔ Checking for cached plan... found
Detected Terraform directory at ./monero/terraform
  ✔ Checking for cached plan... found
Detected Terraform directory at ./tron/terraform
  ✔ Checking for cached plan... found

✔ Calculating monthly cost estimate


Running in "decred/terraform"
"doge/terraform"
"lnbt/terraform"
"ltc/terraform"
"monero/terraform"
"tron/terraform"

Summary: {
  "totalDetectedResources": 30,
  "totalSupportedResources": 6,
  "totalUnsupportedResources": 0,
  "totalUsageBasedResources": 6,
  "totalNoPriceResources": 24,
  "unsupportedResourceCounts": {},
  "noPriceResourceCounts": {
    "aws_alb_target_group": 6,
    "aws_alb_target_group_attachment": 6,
    "aws_lb_listener_rule": 6,
    "aws_security_group": 6
  }
}

Total Monthly Cost:        543.006 USD
Total Monthly Cost (diff): 0
0
0
0
0
67.456 USD

```

### Environment information

* OS:  MacOS
```
$ uname -a
Darwin ip-192-168-0-192.eu-west-1.compute.internal 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64
```

* Tools availability and versions:
```
pre-commit 2.16.0
Terraform v1.0.5
Python 3.9.9
checkov 2.0.645
terraform-docs version v0.16.0 darwin/amd64
terragrunt SKIPPED
terrascan version: v1.12.0
TFLint version 0.33.2
tfsec v0.63.1
```

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```bash
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [--branch, master]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.60.0
    hooks:
      - id: terraform_validate
      - id: infracost_breakdown
        args:
          - --args=--config-file=infracost.yaml
          - --hook-config='.projects[].diff.totalMonthlyCost|tonumber <= 500' 
        verbose: true
```

</details>

**Comment by antonbabenko** [comment]
You have multiple Terraform directories where infracost tried to calculate the cost. You can try to get the total amount across all of them like this:
```
- --hook-config='.diffTotalHourlyCost|tonumber <= 500' 
```

Or limit `path` argument to run just in one directory, like this:
```
- --args=--path=./env/dev
```

You can also call the same hook multiple times with different `path` arguments if you want to have different rules per path.

**Comment by yobooooi** [comment]
Hey thanks for the help but unfortunately I still run into the same problem. I do get the break down when I run `infracost breakdown --config-file=./infracost.yaml --format json | python3 -m json.tool` . I can see that the `diffTotalHourlyCost` values are aggregated. I think that the value I'm specifying in this case `diffTotalMonthlyCost` is not being extracted from the response from `infracost breakdown` so the casting it to a number and comparing it is failing. 

To confirm my assumption I tried to check that the currency is USD ` - --hook-config='.currency == "USD"' ` but pre commit is failing with the same error code.  


` - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.60.0
    hooks:
      - id: terraform_validate
      - id: infracost_breakdown
        args:
          - --args=--config-file=infracost.yaml
          - --hook-config='.diffTotalMonthlyCost|tonumber <= 600.00' 
        verbose: true
`

**Comment by yobooooi** [comment]
infracost breakdown --config-file=./infracost.yaml --format json | jq -r '.diffTotalMonthlyCost'
Detected Terraform directory at ./decred/terraform
  ✔ Checking for cached plan... found
Detected Terraform directory at ./doge/terraform
  ✔ Checking for cached plan... found
Detected Terraform directory at ./lnbt/terraform
  ✔ Checking for cached plan... found
Detected Terraform directory at ./ltc/terraform
  ✔ Checking for cached plan... found
Detected Terraform directory at ./monero/terraform
  ✔ Checking for cached plan... found
Detected Terraform directory at ./tron/terraform
  ✔ Checking for cached plan... found

✔ Calculating monthly cost estimate

67.456




I find this also really weird. I dont know what the issue is now

**Comment by Huncho3511** [comment]
J'ai un mais je sais pas

**Comment by Huncho3511** [comment]
En faite j'ai un problème mais jsais pas si vous pouvez m'aide s'il vous plaît

**Comment by yobooooi** [comment]
@Huncho3511 sure I can help but maybe if you could meet me half way with some english that would help me quite a bit. 

avez vous le même problème ?

**Comment by fellnerse** [comment]
I have the exact same issue
