### ISSUE TITLE
Need terraform_tflint option to not find more paths to run in.

### ISSUE THREAD

**Issue by grimm26** [antonbabenko/pre-commit-terraform#300]
I need a way for terraform_tflint to not descend into subdirectories. I only want it to check the current directory.

 ## Use case
I am using this with terraform module repositories. The module has a `test/` directory that has a test invocation of the module that people can use to verify that their changes will plan out fine. This causes an error when running the pre-commit check.

```
Terraform validate with tflint...........................................Failed
- hook id: terraform_tflint
- exit code: 1


TFLint in test/:
Failed to load configurations. 1 error(s) occurred:

Error: `test` module is not found. Did you run `terraform init`?

  on test/test.tf line 27, in module "test":
  27: module "test" {
```

I ran a `terraform init` in both direcotories, but I think since tflint is being run from `./` it doesn't see that the module is loaded in `./test`.

### How could pre-commit-terraform help solve your problem?

Add an option to disable searching for paths to run the tflint check in. Just run it in `./`

**Comment by grimm26** [comment]
https://github.com/antonbabenko/pre-commit-terraform/pull/125 changed the functionality, causing the breakage. No mention of this change in the PR, only a minor version tick.

**Comment by yermulnik** [comment]
> Add an option to disable searching for paths to run the tflint check in. Just run it in `./`

You can achieve this by adjusting `tflint` hook configuration https://github.com/antonbabenko/pre-commit-terraform/blob/master/.pre-commit-hooks.yaml#L63-L70 like this: `exclude: (\.terraform|test)\/.*$`

**Comment by grimm26** [comment]
@yermulnik Is there a way to do this in my `.pre-commit-config.yaml` or how can I modify the .pre-commit-hooks.yaml for myself?

**Comment by grimm26** [comment]
NM, I firgured it out. I can just add an `excludes` setting in the .pre-commit-config.yaml

**Comment by yermulnik** [comment]
Great to hear you've managed this 👍🏻
