### ISSUE TITLE
Support for tfupdate

### ISSUE THREAD

**Issue by jrottenberg** [antonbabenko/pre-commit-terraform#328]
### Integrate tfupdate 

Run https://github.com/minamijoyo/tfupdate/ on commit to pin the version of terraform and providers.

That will allow users to pin versions without efforts, at least for terraform itself and the providers.

### How could pre-commit-terraform help solve your problem?

I have a simple PR : https://github.com/minamijoyo/tfupdate/pull/63 but could rewrite it to be a bit more dynamic, ie detects the provider and update, overall it does the job. 

If you are interested I can apply it to this repo.

**Comment by MaxymVlasov** [comment]
Hi @jrottenberg 
Yeah, it will be useful.

Check out https://github.com/antonbabenko/pre-commit-terraform/blob/master/.github/CONTRIBUTING.md as a start point and feel free to ask if you'll have any questions.
