### ISSUE TITLE
Make terraform_providers_lock work with terragrunt

### ISSUE THREAD

**Issue by dennislapchenko** [antonbabenko/pre-commit-terraform#331]
### What problem are you facing?

`terraform_providers_lock` does not work with terragrunt

### How could pre-commit-terraform help solve your problem?

Instead of running (from docs):
```
terraform init (in case .terraform directory is not initialised)
terraform providers lock
```

allow running terragrunt equivalents. Perhaps a new hook altogether?

**Comment by yermulnik** [comment]
Since `pre-commit-terraform` may be used w/o `terragrant`, I think it's worth a dedicated hook to implement providers locking using `terragrant`. Please feel free to contribute via PR.
