### ISSUE TITLE
ModuleNotFoundError: No module named 'checkov'

### ISSUE THREAD

**Issue by Walluce** [antonbabenko/pre-commit-terraform#353]
I am getting this error:

```
Traceback (most recent call last):
  File "C:\Users\wallucep\AppData\Local\Programs\Python\Python310\Scripts\checkov.cmd", line 50, in <module>
    from checkov.main import run
ModuleNotFoundError: No module named 'checkov'
```

Please note that checkov is installed and working, but not through pre-commit

**Comment by MaxymVlasov** [comment]
As a moderator of one of the Python chats, I can suggest you use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install), to avoid many problems related to Windows. 

None of us use cmd/PowerShell as a work command line. But you can wait if someone from the community to help you, so I don't close this issue immediately.

**Comment by etiennejeanneaurevolve** [comment]
https://gist.github.com/etiennejeanneaurevolve/1ed387dc73c5d4cb53ab313049587d09
