### ISSUE TITLE
TFLint 0.35 breaks compatibility

### ISSUE THREAD

**Issue by smiller171** [antonbabenko/pre-commit-terraform#354]
### Describe the bug

Unfortunately tflint `0.35` totally breaks compatibility with plugins from `>0.34`. It would be beneficial to have a docker build that has `0.35` other than nightly so we can update our configs.

### How can we reproduce it?

Attempt to run tflint with the following config:

```terraform
plugin "aws" {
  enabled = true
  version = "0.13.2"
  source  = "github.com/terraform-linters/tflint-ruleset-aws"
}
```

### Environment information

* OS:  

* `docker info`:

<details><summary><code>command output</summary>

```bash
INSERT_OUTPUT_HERE
```

</details>

* Docker image tag/git commit:  v1.62.3

* Tools versions. Don't forget to specify right tag in command -  
  `TAG=latest && docker run --entrypoint cat pre-commit:$TAG /usr/bin/tools_versions_info`

```bash
pre-commit 2.16.0
Terraform v1.1.2
checkov 2.0.686
Infracost v0.9.15
terraform-docs version v0.16.0 1f686b1 linux/amd64
terragrunt version v0.35.16
terrascan version: v1.12.0
TFLint version 0.34.0
tfsec 0.63.1
```

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```bash
exclude: ".terraform"
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.64.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
          - --args=--version
      - id: terraform_tflint
        name: tflint init
        verbose: true
        require_serial: true
        args:
          - --args=--init
      - id: terraform_tflint
        name: tflint
        require_serial: true
      - id: terraform_docs
      - id: terraform_validate
        exclude: examples
        args:
          - --args=-json
```

</details>

**Comment by MaxymVlasov** [comment]
Hi
Should be resolved by [image build for v1.64.1](https://github.com/users/antonbabenko/packages/container/pre-commit-terraform/18034528?tag=v1.64.1)
