### ISSUE TITLE
Support for Terraform `plugin_cache_dir`

### ISSUE THREAD

**Issue by bryantbiggs** [antonbabenko/pre-commit-terraform#377]
### What problem are you facing?
I am curious if there is a way to specify the [`plugin_cache_dir`](https://www.terraform.io/cli/config/config-file#provider-plugin-cache) within the pre-commit workflow (most likely through the `TF_PLUGIN_CACHE_DIR` env var)? I suspect this would help speed up some of the workflows where multiple, similar examples are executed and they are all pulling down the same or similar code. I am experimenting with adding it to a [github action workflow](https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/492/files#diff-3c0d80ea54e617ba55ba031dda6fc983852272f93775375ce402a66a03560548R37-R45) but it doesn't accommodate the local user experience

### How could pre-commit-terraform help solve your problem?
Plugin cache dir might help reduce time to evaluate checks for users

**Comment by antonbabenko** [comment]
I ran the benchmark with `plugin_cache_dir` config value set in `~/.terraformrc` for the VPC module locally - 22 seconds. And, without this setting, it takes 1:30 minutes.

I don't think we can wisely set the path for users of these pre-commit hooks, but we can document this potential improvement in README saying that users can set env var like this, for e.g.:

    export TF_PLUGIN_CACHE_DIR="$HOME/.terraform.d/plugin-cache"

**Comment by MaxymVlasov** [comment]
I think we could add to README something like `tips` section, where we can describe some well know and well-documented features like `plugin_cache_dir`. But that will move the focus from hooks usage to tools usage.

Hooks run in a bash environment that is not isolated from the session where they run. So all related `export`'ed env vars will be used.
