### ISSUE TITLE
"Error: `init` is unknown option" when running tflint

### ISSUE THREAD

**Issue by jamiet-msm** [antonbabenko/pre-commit-terraform#378]
### Describe the bug

Every time I try to use the terraform_tflint hook I get an error 

> Error: `init` is unknown option

### How can we reproduce it?

```shell
mkdir demotflint && cd demotflint && git init
touch demo.tf
cat << EOF > .pre-commit-config.yaml
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.70.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
EOF
pre-commit install
git add .
pre-commit
```

On my machine this returns:

```
➜ pre-commit
Terraform fmt............................................................Passed
Terraform validate.......................................................Passed
Terraform validate with tflint...........................................Failed
- hook id: terraform_tflint
- exit code: 2

\e[0m\e[31mCommand 'tflint --init' failed:\e[0m
Failed to parse CLI options. An error occurred:

Error: `init` is unknown option. Please run `tflint --help`
```
### Environment information

* OS:  MacOS

* `uname -a` and/or `systeminfo | Select-String "^OS"` output:

```bash
Darwin C02D6CTCMD6M 19.6.0 Darwin Kernel Version 19.6.0: Sun Nov 14 19:58:51 PST 2021; root:xnu-6153.141.50~1/RELEASE_X86_64 x86_64
```

* Tools availability and versions:

```bash
pre-commit 2.17.0
Terraform v0.14.9
Python 3.8.2
checkov checkov SKIPPED
terraform-docs SKIPPED
terragrunt SKIPPED
terrascan terrascan SKIPPED
TFLint version 0.25.0
tfsec tfsec SKIPPED
```

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```bash
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.70.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
```

</details>

**Comment by yermulnik** [comment]
> TFLint version 0.25.0

Please upgrade your `tfint` to at least [0.29.0](https://github.com/terraform-linters/tflint/blob/master/CHANGELOG.md#0290-2021-06-05) or a better choice would be the [latest version](https://github.com/terraform-linters/tflint/releases/latest).

**Comment by jamiet-msm** [comment]
> > TFLint version 0.25.0
> 
> Please upgrade your `tflint` to at least [0.29.0](https://github.com/terraform-linters/tflint/blob/master/CHANGELOG.md#0290-2021-06-05) or a better choice would be the [latest version](https://github.com/terraform-linters/tflint/releases/latest).

easy as that eh! sorry to bother you :(
