### ISSUE TITLE
Add to the tflint description that deep check is only possible now for AWS

### ISSUE THREAD

**Issue by eternityduck** [antonbabenko/pre-commit-terraform#390]
![image](https://user-images.githubusercontent.com/70644164/170458603-5aede895-6e1d-4679-bf2b-8e77901be7cb.png)

**Comment by antonbabenko** [comment]
Hi Bohdan!

It is completely up to the users of individual tools (`tflint` in this case) to know what kind of parameters are supported.

We should not put such notes in `pre-commit-terraform` and keep track of features available in individual versions.
