### ISSUE TITLE
Terraform hooks for windows

### ISSUE THREAD

**Issue by ayush2708** [antonbabenko/pre-commit-terraform#393]
Sorry for a newbie question.. Is there any way to make these run in Windows as all the hooks are shell scripts . ?.

**Comment by MaxymVlasov** [comment]
Hi
You can use Docker, WSL/WSL2 or stuff that was used before Win10 become live.

If you VS Code guy, I highly recommend you start using WSL2

**Comment by MaxymVlasov** [comment]
403 means that you did not set up access correctly. Check [this doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret), it's should help. Maybe you forgot to install/configure  AZ CLI etc. inside WSL.

When you say "internet not working" do you mean that `ping google.com` and `ping 1.1.1.1` both do not work?
If works only the last command - you fail in DNS resolution, as I know, it's a common WSL issue. Here is the fix:
https://gist.github.com/coltenkrauter/608cfe02319ce60facd76373249b8ca6

In my personal case, it works fine :D 
```bash
➜ cat /etc/wsl.conf 
[automount]
enabled = true
options = "metadata,umask=011"
```

**Comment by MaxymVlasov** [comment]
Think about WSL as about isolated environment, e.g. Virtual Machine, that can have access to files, etc. on the host machine, but has no idea about software and its settings in Windows. 

So you need to set up all needed stuff inside WSL as on the Remote Linux server. You can simply connect to it via [VS Code Remote WSL ext](https://code.visualstudio.com/docs/remote/wsl) and [Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701?hl=uk-ua&gl=UA)

**Comment by ayush2708** [comment]
> 403 means that you did not set up access correctly. Check [this doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret), it's should help. Maybe you forgot to install/configure AZ CLI etc. inside WSL.
> 
> When you say "internet not working" do you mean that `ping google.com` and `ping 1.1.1.1` both do not work? If works only the last command - you fail in DNS resolution, as I know, it's a common WSL issue. Here is the fix: https://gist.github.com/coltenkrauter/608cfe02319ce60facd76373249b8ca6
> 
> In my personal case, it works fine :D
> 
> ```shell
> ➜ cat /etc/wsl.conf 
> [automount]
> enabled = true
> options = "metadata,umask=011"
> ```
For WSL1, I have setup the access correctly. The remote backend for Terraform on Azure is only accessible via Azure VPN ( protected via  Firewall and accessed through Private endpoint ). In windows Storage account endpoint is resolved correctly and request goes from a private IP ( issued via Azure VPN ) and not from Public IP. But from WSL request goes via Public IP rather than private . Hence the issue of 403 . I added my public IP in storage Firewall and tf init started working 
And for WSL2 issue . The thing is network architecture has been changed from WSL1 to 2 . In WSL1 network adapter used Bridged mode however in WSL2 it's NATt'd . Think of it like a Adapter on a VM which is local to it and has no internet access. And yes i tried the below steps which u listed already and many more but didn't work (including resetting the complete IP stack in windows, re-installed wsl etc )

**Comment by ayush2708** [comment]
> Think about WSL as about isolated environment, e.g. Virtual Machine, that can have access to files, etc. on the host machine, but has no idea about software and its settings in Windows.
> 
> So you need to set up all needed stuff inside WSL as on the Remote Linux server. You can simply connect to it via [VS Code Remote WSL ext](https://code.visualstudio.com/docs/remote/wsl) and [Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701?hl=uk-ua&gl=UA)

Yes, I reverted back to WSL1 . Got the terraform init working and now tflint is working as expected . Thank you so much. And yes m using the VS code extension as well :) . 
I may end up opening a seperate issue with Azure Support as to why WSL is not able to resolve private endpoints when connected to Azure VPN.
