### ISSUE TITLE
Check how hard make hooks sh POSIX compatible

### ISSUE THREAD

**Issue by MaxymVlasov** [antonbabenko/pre-commit-terraform#397]
will help: https://github.com/dylanaraps/pure-sh-bible and https://github.com/antonbabenko/pre-commit-terraform/pull/339#issuecomment-1055700715

Related issues that will not exist if make hooks POSIX compatible: https://github.com/antonbabenko/pre-commit-terraform/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3Aarea%2FmacOS+

**Comment by yermulnik** [comment]
Okay.... https://mywiki.wooledge.org/BashPitfalls =)

**Comment by antonbabenko** [comment]
:trollface:

**Comment by MaxymVlasov** [comment]
Depends on #303

**Comment by MaxymVlasov** [comment]
@yermulnik Then, I suppose we can close this issue and stick with bash 3.2.57? 

![image](https://github.com/antonbabenko/pre-commit-terraform/assets/11096782/f5a42ff1-3a47-4650-9b75-30c0766c3aac)


https://github.com/antonbabenko/pre-commit-terraform/pull/620/files#r1485091544

**Comment by yermulnik** [comment]
@MaxymVlasov I guess we indeed can and, if we explicitly rely upon `bash` in shebang strings, care only about cross-compatibility between Bash v3 and more modern versions of Bash.
