### ISSUE TITLE
Control recursion for `terraform_docs` hook.

### ISSUE THREAD

**Issue by robert-twingate** [antonbabenko/pre-commit-terraform#420]
Currently the `terraform_docs` hook will process all subdirectories, but that's not always desired.  In my case I have a terraform-modules monorepo where each module has an `examples` directory that contains terraform code, but I don't want docs generated for the examples.  I would like to limit recursion to the top level only.

**Comment by yermulnik** [comment]
You're looking for `exclude` parameter from the `pre-commit` per se: https://pre-commit.com/#pre-commit-configyaml---hooks
See #391 for alike use case.
Also based on #419 you may need to enclose `exclude` parameter value into single quotes to safeguard from unexpected interpolation.

**Comment by yermulnik** [comment]
> I would like to limit recursion to the top level only.

Or alternatively you may amend `include` parameter to only process files in the root directory of your repo, e.g. `files: '^([^/]+\.tf|\.terraform\.lock\.hcl)$'` (needs testing).
