### ISSUE TITLE
Use the latest terraform version 

### ISSUE THREAD

**Issue by Tony-Proum** [antonbabenko/pre-commit-terraform#435]
### Describe the bug

when the hook is running it prevent me to commit because of experimental features flag that needs to be added in order to validate the terraform code. The problem is that I had to remove those flag because they are not needed anymore in the terraform 1.3.0 version.

### How can we reproduce it?

create a new terraform project that use the optional feature : 

```
variable "test" {
  type = list(
    object({
      test = optional(string)
      name = string,
      }))
}
```

using terraform version 1.2 you'll have to activate an experimental flag using  : 

```
terraform {
    experiments  = [module_variable_optional_attrs]
}
```
upgrading the terraform version to 1.3 the flag need to be remove. Then the hook returns this kind of errors : 

``` 
Error: Optional object type attributes are experimental
│ 
│   on variables.tf line 102:
│  102: variable "test" {
│ 
│ This feature is currently an opt-in experiment, subject to change in future
│ releases based on feedback.
│ 
│ Activate the feature for this module by adding
│ module_variable_optional_attrs to the list of active experiments.

```

**Comment by antonbabenko** [comment]
Hi @Tony-Proum !

You can use the `nightly` image if you want to be on edge, but I have also just triggered GitHub Actions to get `latest` tag updated, too.

https://github.com/antonbabenko/pre-commit-terraform/pkgs/container/pre-commit-terraform

**Comment by Tony-Proum** [comment]
@antonbabenko Thank you !

**Comment by Tony-Proum** [comment]
@antonbabenko do you plan to tag/release a new version using this container version ?

**Comment by antonbabenko** [comment]
Yes, when there will be a new feature or a fix in the code.

**Comment by Tony-Proum** [comment]
supporting version 1.3 of terraform could be the new feature 😁

**Comment by antonbabenko** [comment]
I know, we need to make any change in the code to trigger a new release. This is how the GH Actions release process works now ;)

**Comment by Tony-Proum** [comment]
How ok lol I didn't thought about that ! 👍🏽
