### ISSUE TITLE
[`pre-commit`, `terragrunt`] Top level terragrunt.hcl fail terragrunt validate command

### ISSUE THREAD

**Issue by natsumemaya** [antonbabenko/pre-commit-terraform#440]
### Describe the bug
In this tree structure Top level  `terragrunt.hcl` file can't pass `terragrunt validate` command. It can't find refers to the down level files such as `"common.hcl"`, `"env.hcl`, `"unique.hcl"`

So `pre-commit` command doen't work too with same error.

```
├── terragrunt.hcl
├── envs
│      ├── common.hcl
│      ├── developers
│      │      ├── devone
│      │      │   ├── terragrunt.hcl
│      │      │   └── unique.hcl
│      │      ├── devtwo
│      │      │   ├── terragrunt.hcl
│      │      │   └── unique.hcl
│      ├── staging
│      │      ├── env.hcl
│      │      ├── stageone
│      │      │   ├── terragrunt.hcl
│      │      │   └── unique.hcl
│      │      ├── stagetwo
│      │      │   ├── terragrunt.hcl
│      │      │   └── unique.hcl
├── locals.tf
├── main.tf
├── modules
└── variables.tf
```
```bash
ERRO[0000] Error: Error in function call
      
ERRO[0000]   on /home/iuliia/myproject/terragrunt.hcl line 36, in locals: 
ERRO[0000]   36:   common_vars      = read_terragrunt_config(find_in_parent_folders("common.hcl")) 
ERRO[0000]                                              
ERRO[0000] Call to function "find_in_parent_folders" failed: ParentFileNotFound: Could not find a common.hcl in any of the parent folders of /home/iuliia/myproject/terragrunt.hcl. Cause: Traversed all the way to the root..
 
ERRO[0000] Encountered error while evaluating locals in file /home/iuliia/myproject/terragrunt.hcl 
ERRO[0000] /home/iuliia/myproject/terragrunt.hcl:36,45-68: Error in function call; Call to function "find_in_parent_folders" failed: ParentFileNotFound: Could not find a common.hcl in any of the parent folders of /home/iuliia/myproject/terragrunt.hcl. Cause: Traversed all the way to the root.. 
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```
### How can we reproduce it?

You can try run `terragrunt validate` on the top level folder, and get same error with the `pre commit` command. We can exclude top level .hcl file explicetly in the `pre-commit.yaml` and get skip:
```yaml
  - id: terraform_tfsec
  - id: terragrunt_validate
    exclude: terragrunt.hcl
```
```bash
Terragrunt validate..................................(no files to check)Skipped
```
But what the point? I need check this file! this is the major file i need to check!
And how can i skip only this file but not the other ones that down the tree, i was trying to guess with the option `files:` in configuration, but failed (files skipe validate check despite changes inside the files). 
RegExp: `files:  (\/envs\/[a-z]+\/[a-z]+\/terragrunt.hcl)$`
```
terragrunt -v
terragrunt version v0.38.12
pre-commit --version
pre-commit 2.20.0
```

**Comment by yermulnik** [comment]
I'm not familiar with Terragrunt, though does https://github.com/transcend-io/terragrunt-atlantis-config/issues/48#issuecomment-707433386 look like a fix for this particular issue with `terrafrunt`'s validate functionality?

**Comment by MaxymVlasov** [comment]
Try
```yaml
  - id: terragrunt_validate
    exclude: "^terragrunt.hcl"
```

**Comment by MaxymVlasov** [comment]
>And how can i skip only this file 

```yaml
  - id: terraform_tfsec
  - id: terragrunt_validate
    exclude: "^terragrunt.hcl"
```


>files skipe validate check despite changes inside the files

That's expected.

If you need always validate things that not changed, use [`always_run: true`](https://pre-commit.com/#config-always_run)

**Comment by natsumemaya** [comment]
` exclude: "^terragrunt.hcl"` works thanks, but again what is the whole point of `terragrunt_validate` in this case, if i can't check the major file 😞

**Comment by MaxymVlasov** [comment]
>... Top level terragrunt.hcl ... can't find refers to the down level files such as "common.hcl", "env.hcl, "unique.hcl"

And it shouldn't. In Terragrunt is no function to lookup in depth, because it's too co

That's a Terragrunt error, not hook error.
```bash
ERRO[0000] Error: Error in function call
      
ERRO[0000]   on /home/iuliia/myproject/terragrunt.hcl line 36, in locals: 
ERRO[0000]   36:   common_vars      = read_terragrunt_config(find_in_parent_folders("common.hcl")) 
ERRO[0000]                                              
ERRO[0000] Call to function "find_in_parent_folders" failed: ParentFileNotFound: Could not find a common.hcl in any of the parent folders of /home/iuliia/myproject/terragrunt.hcl. Cause: Traversed all the way to the root..
```

You need to revisit what is in your root lvl `terragrunt.hcl`, and remove all things like:
```hcl
find_in_parent_folders("common.hcl")
```
because the root folder has no parents.
