### ISSUE TITLE
Exclude for terraform_fmt hook

### ISSUE THREAD

**Issue by jay-grindrod-cts** [antonbabenko/pre-commit-terraform#453]
Can you please add an exclude to the `terraform_fmt` hook.

We have a symlink for our `secrets.tfvars` file, and I currently get an (expected) error saying the hook can't read the file.

It would be good to be able to exclude this 👍🏻 

Thanks a lot

**Comment by yermulnik** [comment]
Local exclusion go into particular hook config:
* https://pre-commit.com/#pre-commit-configyaml---hooks
* https://github.com/antonbabenko/pre-commit-terraform/blob/master/.pre-commit-hooks.yaml#L16
