### ISSUE TITLE
continue on failed tflint

### ISSUE THREAD

**Issue by FernandoMiguel** [antonbabenko/pre-commit-terraform#455]
### What problem are you facing?

I would like for tflint tests to not fail the entire pre-commit run, so that I can later commit and push those changes back to the branch

**Comment by yermulnik** [comment]
I think you should be good to add `--force` to `terraform_tflint` hook config to achieve what you're looking for.
You can find an example of how to pass it to hook here: https://github.com/antonbabenko/pre-commit-terraform#terraform_tflint

Please circle back with whether this is what you mean. Thanks.

**Comment by MaxymVlasov** [comment]
+ `verbose: true`, or you always will see `Passed` status for the tflint hook.

Other option - `SKIP=terraform_tflint git commit` 
https://pre-commit.com/#temporarily-disabling-hooks
