### ISSUE TITLE
Docker image not compatible with platform (linux/arm64/v8)

### ISSUE THREAD

**Issue by enzsadeddine** [antonbabenko/pre-commit-terraform#458]
### Describe the bug

When we launch the docker pre-commit image on a macbook M1 we encounter a warning and abnormal execution slowness that are not present on the linux/amd64 platform. is it possible to create an image compatible with the paltform linux/arm64/v8 ?

### How can we reproduce it?

Log:

```bash
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[INFO] Initializing environment for https://github.com/antonbabenko/pre-commit-terraform.git.
```

### Environment information

* OS:  MacOS
*  Platform: arm64
* Docker TAG: latest

**Comment by MaxymVlasov** [comment]
Yeah, it is not compatible, as specified in pre-req in the first line https://github.com/antonbabenko/pre-commit-terraform#1-install-dependencies.

And, yes, it is possible to create a compatible and maintainable image at the same time, but right now it's not our priority.
So if you'd like to spend some time on it, we would greatly appreciate it.
