### ISSUE TITLE
provider random password resource number to numerical change.

### ISSUE THREAD

**Issue by omerfsen** [antonbabenko/pre-commit-terraform#459]
### What problem are you facing?

With https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password version 3.3.0 they have changed from **number** to **numerical** string. This can be checked on https://registry.terraform.io/providers/hashicorp/random/3.3.0/docs/resources/password

When we use latest version of pre-commit-terraform ([v1.77.0](https://github.com/antonbabenko/pre-commit-terraform/releases/tag/v1.77.0))  it complains that it does not recognize *numerical* string. It would be nice that it supports both string.

**Comment by yermulnik** [comment]
Hey @omerfsen 
`pre-commit-terraform` is a **wrapper** for other tools which do lint code and alike.
To help identify which exact tool is failing for you we need more info. First off please post output of `pre-commit-terraform` where the error you faced is visible.
