### ISSUE TITLE
terraform_docs does not like "description"

### ISSUE THREAD

**Issue by antonbabenko** [antonbabenko/pre-commit-terraform#47]
Since [v1.13.0](https://github.com/antonbabenko/pre-commit-terraform/releases/v1.13.0) when `terraform_docs` hook began to work with Terraform 0.12 syntax, the `awk` script which is used to do the magic for Terraform 0.12 types does not like variables or outputs named "description".

As a result, this module - https://github.com/terraform-aws-modules/terraform-aws-security-group - can't use this hook.

## How to reproduce?
1. Clone this repository
1. Clone failing terraform-aws-module repository - https://github.com/terraform-aws-modules/terraform-aws-security-group
1. `cd terraform-aws-security-group`
1. `pre-commit try-repo  ~/cloned-repo/pre-commit-terraform terraform_docs --verbose --all-files`

## Error:
```
At 1:17: Unknown token: 1:17 IDENT var.description
```

@cytopia, could you take a look at this?

**Comment by cytopia** [comment]
Is this the affecting line: https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/variables.tf#L26 ?

**Comment by antonbabenko** [comment]
I don't think so, but I also can't identify exactly which line makes the problem.

Here is the beginning of produced tf-file after `awk` script:
```
  description = var.description
  description = var.description
  description      = var.rules[var.ingress_rules[count.index]][3]
  description      = var.rules[var.computed_ingress_rules[count.index]][3]
  description = lookup(
  description = lookup(
  description = lookup(
  description = lookup(
  description = lookup(
  description = lookup(
  description = lookup(
  description = lookup(
  description      = var.rules[var.egress_rules[count.index]][3]
  description      = var.rules[var.computed_egress_rules[count.index]][3]
  description = lookup(
  description = lookup(
  description = lookup(
  description = lookup(
  description = lookup(
  description = lookup(
  description = lookup(
  description = lookup(
output "this_security_group_id" {
  description = "The ID of the security group"
}
output "this_security_group_vpc_id" {
  description = "The VPC ID"
}
output "this_security_group_owner_id" {
  description = "The owner ID"
}
output "this_security_group_name" {
  description = "The name of the security group"
}
output "this_security_group_description" {
  description = "The description of the security group"
}
//output "this_security_group_ingress" {
//}
//output "this_security_group_egress" {
variable "rules" {
  description = "Map of known security group rules (define as 'name' = ['from port', 'to port', 'protocol', 'description'])"
  type = "map(list(any))"
...................
```

**Comment by cytopia** [comment]
I've just played around a little and got a few bugs fixed, but it seems to be more complicated as expected and one must also take into account comments, as well as brackets within strings. I keep you posted on the progress.

**Comment by cytopia** [comment]
@antonbabenko I've added another version here: https://github.com/cytopia/docker-terraform-docs/pull/13

I will still need to add all discovered edge cases in the test directory, so I can ensure this is stable for the currently discovered issues. Once it plays well, I'll update the PR at: https://github.com/cloudposse/build-harness/pull/155

Feel free to copy the file over and see how it works in your projects

**Comment by cytopia** [comment]
**Update**

I've tested main module, all sub-modules as well as all examples in https://github.com/terraform-aws-modules/terraform-aws-security-group/ very quickly via:

```
d=$(pwd); for i in $(/bin/ls); do if test -d $d/$i; then cd $d/$i; if ! docker run --rm -v $(pwd):/data cytopia/terraform-docs terraform-docs-012 md .;then exit 1;fi ; else echo $d/$i; fi  done
```


Everything generates without any errors.

I am not sure what arguments you add to `terraform-docs`, so you should probably test it via the pre-commit-terraform project and ensure no changes are present after the generation.

**Comment by antonbabenko** [comment]
[v1.15.0](https://github.com/antonbabenko/pre-commit-terraform/releases/v1.15.0) has been released with the fix.
