### ISSUE TITLE
terraform_docs pukes when a default is set to null

### ISSUE THREAD

**Issue by grimm26** [antonbabenko/pre-commit-terraform#49]
Need to improve the awk hack to probably convert `default = null` to `default = "null"` so terraform-docs can parse it.

Right now I get:
`2019/06/17 17:41:15 At 17:17: Unknown token: 17:17 IDENT null`

**Comment by antonbabenko** [comment]
[v1.15.0](https://github.com/antonbabenko/pre-commit-terraform/releases/v1.15.0) has been released with the fix.
