### ISSUE TITLE
tfsort support

### ISSUE THREAD

**Issue by jmreicha** [antonbabenko/pre-commit-terraform#501]
### What problem are you facing?

Having a way to automatically sort variables inside variables.tf files would be a very useful check/lint for organizing and cleaning up Terraform codebases. I would be curious if there are others out there that face this issue and wonder if it would be worth adding support for a tool to do this.

### How could pre-commit-terraform help solve your problem?

From the [tfsort](https://github.com/AlexNabokikh/tfsort) project:

> tfsort is a command-line utility designed for meticulous engineers who prefer to keep their Terraform variables and outputs sorted in alphabetical order.
>
> tfsort also corrects any spacing issues between the blocks and removes any leading or trailing new lines in the file.

The idea would be to have a hook to do this via `pre-commit`. Thoughts?

**Comment by MaxymVlasov** [comment]
Hmm, relates to #446?
And duplicates of #111

@jmreicha  If you like to have that hook and it has some unique pluses compared with the suggested in #446 solution - feel free to implement it. In [CONTRIBUTING.md](https://github.com/antonbabenko/pre-commit-terraform/blob/master/.github/CONTRIBUTING.md#add-new-hook) you will find things to start from
