### ISSUE TITLE
terraform_fmt and terraform_docs reporting no files to check

### ISSUE THREAD

**Issue by 3choBoomer** [antonbabenko/pre-commit-terraform#502]
### Describe the bug
Running `pre-commit run --all-files` with config for `terraform_fmt` and `terraform_docs` in a directory with several `.tf` files is reporting `(no files to check)Skipped`

<img width="874" alt="image" src="https://user-images.githubusercontent.com/521828/229156801-742201e9-d65c-46ae-ba27-36b7c0c8b270.png">

### Environment information

OS: MacOS
```bash
Darwin C02CC8GFMD6N 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
```

* Tools availability and versions:

```bash
GNU bash, version 5.2.15(1)-release (x86_64-apple-darwin21.6.0)
pre-commit 3.2.1
Terraform v0.14.11
Python 3.10.6
Python 3.10.6
checkov 2.3.135
terraform-docs version v0.16.0 darwin/amd64
terragrunt SKIPPED
terrascan version: v1.18.0
TFLint version 0.45.0
+ ruleset.terraform (0.2.2-bundled)
tfsec v1.28.1
tfupdate 0.6.7
hcledit 0.2.6
```

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```bash
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
      args:
        - --args=-diff
        - --args=-recursive
    - id: terraform_docs
    - id: terraform_tfsec
```

</details>

**Comment by MaxymVlasov** [comment]
Hi

What `git status` show?

**Comment by MaxymVlasov** [comment]
And, in case it is a new repo, you need as least Stage files

`git add -A && pre-commit run -a`
