### ISSUE TITLE
Add terraform-cleaner hook to commit only used variables

### ISSUE THREAD

**Issue by antonbabenko** [antonbabenko/pre-commit-terraform#504]
### What problem are you facing?

It would be great to have a hook that checks whether variables are used.

https://github.com/sylwit/terraform-cleaner does the thing but it requires some extra work (return exit code, less verbosity, ignore subdirectories, etc).

**Comment by sylwit** [comment]
I would be more than happy to do the extra work and add the tool to pre-commit. Here are a few comments to open the discussion:

- On Reddit, someone mentioned that this feature already exists in tflint.
- What should we consider for the exit code? Currently, the output returns the number of usages for each variable and local. The exit code could make sense only with the --unused-only flag.
- Regarding verbosity, have you looked at the --locals and --variables flags?
- Ignoring subdirectories could be a new feature to consider.

**Comment by MaxymVlasov** [comment]
Use `terraform_tflint` for that


`.tflint.hcl`

```hcl
rule "terraform_unused_declarations" {
    # Disallow variables, data sources, and locals that are declared but never used
    enabled = true
}
```
