### ISSUE TITLE
Use docker build or pull  to install hooks not working for MacOS

### ISSUE THREAD

**Issue by seifrajhi** [antonbabenko/pre-commit-terraform#505]
### Describe the bug
I was trying to install the hooks using docker pull image method in my macOS, but I faced error.
So I tried second method to build from scratch the image, and I also received an error

### How can we reproduce it?

Below screenshots for the error messages for both methods:

1. using docker pull

<img width="970" alt="docker_pull" src="https://user-images.githubusercontent.com/26981510/232565994-27754495-0db1-49ba-be9e-f7000a95f4cb.png">

2. Build from scratch

<img width="1335" alt="docker_build" src="https://user-images.githubusercontent.com/26981510/232566023-905800b5-b925-4de7-a41c-bd25bfd6e275.png">

Do you have long logs to share? Please use collapsible sections, that can be created via:

#### commands used

```bash
# pull
TAG=latest                                                                                                               
docker pull ghcr.io/antonbabenko/pre-commit-terraform:$TAG

# build from sratch
docker build -t pre-commit-terraform --build-arg INSTALL_ALL=true .

```

### Environment information

* OS:  MacOS

* `docker info`:

<details><summary><code>command output</summary>

```bash
Client:
 Context:    colima
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.17.2
    Path:     /Users/saifeddine.rajhi/.docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 0
  Paused: 0
  Stopped: 9
 Images: 38
 Server Version: 20.10.20
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: 5fd4c4d144137e991c4acebb2146ab1483a97925
 init version: 
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.15.82-0-virt
 Operating System: Alpine Linux v3.16
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 1.93GiB
 Name: colima
 ID: BVT6:QF2F:DTGD:HBD7:7LGL:UYYX:EZA6:Y5UP:ONZI:76NY:7GFR:FMCX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
</details>

**Comment by MaxymVlasov** [comment]
arm64 not supported yet, use amd64 instead

>1. Install dependencies
>[pre-commit](https://pre-commit.com/#install), [terraform](https://www.terraform.io/downloads.html), [git](https://git-scm.com/downloads), POSIX compatible shell, Internet connection (on first run), x86_64 compatible operation system ...

Also, you may be interested in #496
