### ISSUE TITLE
Way to just run terraform validate in different directory

### ISSUE THREAD

**Issue by tmccombs** [antonbabenko/pre-commit-terraform#522]
### What problem are you facing?
I have a repository that has a terraform module that uses provider configuration aliases (see https://github.com/antonbabenko/pre-commit-terraform#terraform_validate).  Unfortunately, neither of the workarounds suggested are really what I want. If I exclude the root directory, then, if I understand how pre-commit exclude works, then it won't validate the example directory if I only make changes in the root directory.  But generating a provider file creates a stray file, and means that my local pre-commit hook works differently than the my CI job (which just validates the example directory). 

### How could pre-commit-terraform help solve your problem?
I'd like to have a way to validate in the example directory when there is a change to a file in the root directory.

**Comment by MaxymVlasov** [comment]
Please show your

> CI job (which just validates the example directory).

**Comment by MaxymVlasov** [comment]
Well, you just hardcoded some path inside CI

You can do it in pre-commit too.

Provide something like

```yaml
- id: terraform_validate
  files: ^examples/example1
  always: true
```

**Comment by tmccombs** [comment]
I finally got to work. Note: you need to use `always_run` not `always`
