### ISSUE TITLE
[pre-commit] Run terraform_tflint hook on all .tf and .tfvars file regardless of whether something changed or not

### ISSUE THREAD

**Issue by sunnygoel87** [antonbabenko/pre-commit-terraform#531]
### What problem are you facing?

We would like to run `terraform_tflint` hook on all `.tf` and `.tfvars` files present in `infrastructure` directory every-time we do perform `git commit` operation, regardless of whether something changed in those files or not. 

Here is how we've configured the `.pre-commit-config.yaml` file. Could you please review the `files` field as well for `terraform_tflint` hook and let me know if regex is not correct? Thanks. 

`.pre-commit-config.yaml`:

<details><summary>file content</summary>

```bash
# https://pre-commit.com/index.html#install
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.80.0
    hooks:
      - id: terraform_tflint
        files: ^infrastructure/
        args:
          - --args=--module
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
```

</details>

Since there was no change in any `.tf` and `.tfvars` files so when I did `git commit` after implementing the necessary changes in the project for `terraform_tflint` hook, it threw the following line in the terminal.

*Terraform validate with tflint.......................(**no files to check**)Skipped*

### How could pre-commit-terraform help solve your problem?

By running `pre-commit run -a` command manually in IDE, we're able to ensure that all `.tf` and `.tfvars` files pass all the checks enforced by `tflint`. And we would like `terraform_tflint` hook to provide the same experience as part of `git commit` operation. Not sure whether hook currently supports this capability or not. If it does, then please let me know what additional attributes do i need to set in `.pre-commit-config.yaml` file. Thanks a lot for your help.

**Comment by yermulnik** [comment]
Is `always_run` pre-commit framework option what you're looking for?
See https://pre-commit.com/#config-always_run
