### ISSUE TITLE
Backend initialization required when using terragrunt_validate prehook

### ISSUE THREAD

**Issue by ecoupal-believe** [antonbabenko/pre-commit-terraform#536]
### Describe the bug

Here is my precommit config:

![image](https://github.com/antonbabenko/pre-commit-terraform/assets/103646557/45d90d94-81cf-45e8-8f73-f7362521bdc9)

When using this docker command;
`docker run --rm -v $(pwd):/lint -w /lint ghcr.io/antonbabenko/pre-commit-terraform:latest run -a`

I get a lot of this error:

![image](https://github.com/antonbabenko/pre-commit-terraform/assets/103646557/ad68858a-1e23-467c-9acb-8f7fda171e6b)

Everything works fine when I'm executing:
`terragrunt run-all validate`

Any idea why ?

**Comment by MaxymVlasov** [comment]
Hook looks fine
https://github.com/antonbabenko/pre-commit-terraform/blob/ae5cbe0342617310b0491146d51573f2f4c93705/hooks/terragrunt_validate.sh#L60

Theoretically, you could need to provide AWS credentials inside the container by volume or environment variables.


If you need any future guidance, please provide details specified in [the issue template](https://github.com/antonbabenko/pre-commit-terraform/blob/master/.github/ISSUE_TEMPLATE/bug_report_docker.md?plain=1), which you ignored. And prefer to use text over images whenever possible.
