### ISSUE TITLE
Add functionality for gitlab-slack integration 

### ISSUE THREAD

**Issue by astanfel** [antonbabenko/pre-commit-terraform#556]
### What problem are you facing?

I would like to be able to subscribe to releases for this repo in slack using the gitlab slack integration. 

https://github.com/integrations/slack

### How could pre-commit-terraform help solve your problem?

I believe that the app just needs to be installed by an owner of the repo for me to be able to do this.

**Comment by astanfel** [comment]
@antonbabenko Should be a really small thing for you to add to this repo.

**Comment by yermulnik** [comment]
@astanfel This integration is what you install into your Slack workspace rather than into GH repo. Please refer to https://github.com/integrations/slack#installation for installation instructions.

**Comment by astanfel** [comment]
This works for other github repos for the app that I already have, just not for this repo. 

<img width="426" alt="Screenshot 2023-08-15 at 4 22 29 PM" src="https://github.com/antonbabenko/pre-commit-terraform/assets/16292951/8db286e8-dd3d-4d58-9004-71fa6c4f7839">
<img width="660" alt="Screenshot 2023-08-15 at 4 22 42 PM" src="https://github.com/antonbabenko/pre-commit-terraform/assets/16292951/c47e0b3c-c121-4b50-86d4-961723cbb1d0">

**Comment by astanfel** [comment]
@yermulnik I believe that there is something that needs to be done to the repo itself prior to others being able to subscribe using the integration

**Comment by astanfel** [comment]
<img width="669" alt="Screenshot 2023-08-15 at 4 27 05 PM" src="https://github.com/antonbabenko/pre-commit-terraform/assets/16292951/b1de90ff-27ce-408b-aa59-ad87ac2e72e8">


@yermulnik Here is is working on another repo, I think you just might need to add the github-actions bot to your repo

**Comment by yermulnik** [comment]
> This works for other github repos for the app that I already have, just not for this repo.

That's weird. It's a first time I see a request to install this Slack app to a repo 😲 https://github.com/integrations/slack#installation doesn't have any bit in this regard too 😕 

I'm leaving this to @antonbabenko as he's the owner of this GH repo.

**Comment by antonbabenko** [comment]
I agree with @yermulnik . I don't think I need to change anything. It would be just weird from GitLab/GitHub/Slack if someone wants to subscribe to a random repository.

**Comment by astanfel** [comment]
@antonbabenko @yermulnik how could I go about subscribing to when a new release for the repo happens? I am looking for a consolidated approach to watching repos that my team cares about. 

This is something that I've found works for other public repos for things like terraform providers that we want to know when updates are pushed out.

**Comment by antonbabenko** [comment]
For example, click on "Watch" on the repository homepage, and you will receive emails.

https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/viewing-your-subscriptions

**Comment by yermulnik** [comment]
@astanfel Have you tried following the link by clicking green `Install GitHub App` button? It should lead to https://github.com/apps/slack/installations/new and you should be able to proceed from there by installing it into your GH space I guess. Ref: https://github.com/integrations/slack/issues/559

**Comment by yermulnik** [comment]
@astanfel 
> I have the integration already installed so that doesn't make sense.

So you didn't try what I asked for and don't want to?
Given this experience of yours we'd be able to figure out whether @antonbabenko needs to do that or it is sufficient for a "consumer" to simply install GH integration into their own GH org or personal account.

**Comment by MaxymVlasov** [comment]
@astanfel you could try solution specified here: https://github.com/integrations/slack/issues/397#issuecomment-655912742

`/feed subscribe https://github.com/antonbabenko/pre-commit-terraform/releases.atom`

https://slack.com/help/articles/218688467-Add-RSS-feeds-to-Slack

**Comment by MaxymVlasov** [comment]
But from my perspective, you just need to setup Renovate to update your pre-commit deps, and that's all. You'll read deps changes inside PR

For example: https://github.com/antonbabenko/pre-commit-terraform/pull/479


You can start from https://github.com/SpotOnInc/renovate-config/

**Comment by yermulnik** [comment]
@antonbabenko It looks like repo owner indeed needs to install Slack app for the first time (a one-off thing I think): https://github.com/integrations/slack/issues/397#issuecomment-369678911
Could you please do it by following https://github.com/apps/slack/installations/new ? Others may benefit from this too (I'm among those users who use Slack GH integration to watch after actions in some repos I want to be notified about). Thanks.

> you just need to setup Renovate to update your pre-commit deps

@MaxymVlasov It's not that everything lives in GH 😺 This request is about yet another option to get notifications. And this option is indeed quite widely used as far as I know. Let's allow `pre-commit-terraform` users to utilize this option too.

**Comment by MaxymVlasov** [comment]
Renovate is cross-platform :)

**Comment by yermulnik** [comment]
> Looks like subscribing to the feed works. Thanks @MaxymVlasov !

These two options have different scope and functionality. If your only goal is to get **sporadic** notifications on releases, then you should be fine with `/feed` Slack's integration.

**Comment by yermulnik** [comment]
> Renovate is cross-platform :)

`s/GH/VCS/`
My comment was not about GH, GitLab, or whichever VCS people use, but about things existance outside version control systems.
