### ISSUE TITLE
terraform_docs hook throwing errors depending on terraform format.

### ISSUE THREAD

**Issue by bosmak** [antonbabenko/pre-commit-terraform#56]
Hi All,

I had this strange problem with the hook that it would throw me
```
Terraform fmt............................................................Passed
Terraform docs...........................................................Failed
hookid: terraform_docs

2019/07/17 16:41:09 At 6:4: illegal char
```

Trying to debug it I checked the file on /tmp folder. Where I discovered which line was causing the problem.
```hcl-terraform
...
     3	 }
     4	output "kubeconfig" {
     5	  description = "Kubernetes configuration file for kubectl"
     6	  })
     7	output "name" {
...
```

On the original terraform file this had been declared in the following manner
```hcl-terraform
output "kubeconfig" {
  description = "Kubernetes configuration file for kubectl"
  value = templatefile("${path.module}/templates/kubeconfig.tpl", {
    cluster_name     = var.name
    cluster_endpoint = aws_eks_cluster.this.endpoint
    cluster_ca_data  = aws_eks_cluster.this.certificate_authority[0].data
  })
}
```

Changing this to

```hcl-terraform
output "kubeconfig" {
  description = "Kubernetes configuration file for kubectl"
  value = templatefile("${path.module}/templates/kubeconfig.tpl",
    {
      cluster_name     = var.name
      cluster_endpoint = aws_eks_cluster.this.endpoint
      cluster_ca_data  = aws_eks_cluster.this.certificate_authority[0].data
    }
  )
}
```
solved the problem.

I'm running terraform >0.12.0 so I believe this may happen because of the terraform_0.12 hack.

**Comment by antonbabenko** [comment]
@Bosmak Thanks for reporting this issue!

@cytopia It looks we have another problem case with awk hack. Could you please take a look into it?

**Comment by straubt1** [comment]
Bump

**Comment by konstantin-recurly** [comment]
Is this one still relevant?
It seems that this one could be resolved as well.
@straubt1  Would you, please, check if this still fails for you with the latest release and the latest terraform-docs.

**Comment by straubt1** [comment]
@konstantin-recurly 
Quick check here and it seems the terraform_docs_replace is working well, however terraform_docs is successful, but doesnt insert anything into the README.md.

Overall this is workable for my use case, many thanks on the update!
