### ISSUE TITLE
Backend config in `terraform_validate` for `terraform init`

### ISSUE THREAD

**Issue by darshans2403** [antonbabenko/pre-commit-terraform#564]
### What problem are you facing?

Upon running `terraform_validate` , It is running `terraform init` but I have different backend file name( `dev-backend.tfvars `instead of `backend.tfvars` ). It doesnt have support to pass the backend file explicitly. All I want to run is `terraform init
 --backend-config=dev-backend.tfvars` as a part of `terraform_validate`. 

### How could pre-commit-terraform help solve your problem?

Having flag to pass the backend files I can pass multiple backend files and still able to run terraform validate for my applications.

**Comment by yermulnik** [comment]
This is probably what you're looking for, isn't it?
https://github.com/antonbabenko/pre-commit-terraform/issues/564
![изображение](https://github.com/antonbabenko/pre-commit-terraform/assets/1274789/3360379f-c122-4d0d-baae-f7a852b1d523)

**Comment by darshans2403** [comment]
Nope.. This is for upgrade command and lockfile which are different commands than passing backend-file. 

`--tf-init-args=-upgrade` --> `terraform init -upgrade`
`--tf-init-args=-lockfile=readonly` --> `terraform init -lockfile=readonly`

I am looking for something like this 

```
      - id: terraform_validate
        args:
          - --tf-init-args=--backend-config=dev-backend.tfvars
```

Tried above but didnt work.  getting this error. 

```
Terraform validate.......................................................Failed
- hook id: terraform_validate
- exit code: 1

getopt: unrecognized option '--backend-config'
```

Valid command:  `terraform init --backend-config=dev-backend.tfvars`.

**Comment by MaxymVlasov** [comment]
From 
https://developer.hashicorp.com/terraform/cli/config/environment-variables#tf_cli_args-and-tf_cli_args_name
and 
https://github.com/antonbabenko/pre-commit-terraform#all-hooks-set-env-vars-inside-hook-at-runtime

try

```yaml
- id: terraform_validate
  args:
    - --env-vars=TF_CLI_ARGS="-backend-config=dev-backend.tfvars"
```

**Comment by MaxymVlasov** [comment]
Also, you could try

```yaml
      - id: terraform_validate
        args:
          - --tf-init-args=-backend-config=dev-backend.tfvars
```

(with `-backend-config`, not `--backend-config`)

or/and add `''`:

```
- --tf-init-args='-backend-config=dev-backend.tfvars'
- --tf-init-args='--backend-config=dev-backend.tfvars'
```
