### ISSUE TITLE
`terraform_validate` is slow on a mono repo

### ISSUE THREAD

**Issue by djgoku** [antonbabenko/pre-commit-terraform#567]
### What problem are you facing?

I currently use `pre-commit-terraform` and `terraform_validate` in a mono repository. Our validates are starting to take 5ish total minutes to run.

### How could pre-commit-terraform help solve your problem?

I looked around the repository to see if there was a solution for only running `terraform_validate` on the folders that contained changes.

**Comment by MaxymVlasov** [comment]
`terraform_validate` by default runs only on dirs which contains changes.

If you'd like to execute tf validate quicker  - be sure that you have cached modules and providers and if you use TF 1.4+ - have lockfile.
