### ISSUE TITLE
terraform_docs failing on presence of README.md past v1.7.3

### ISSUE THREAD

**Issue by cloudartisan** [antonbabenko/pre-commit-terraform#57]
Here is the simplest example I could make of the problem:

![image](https://user-images.githubusercontent.com/295402/62518197-509dac00-b86c-11e9-9c5c-5038d24bcb7f.png)

Here are some tests of various versions using a `README.md` with the begin/end tags.

![image](https://user-images.githubusercontent.com/295402/62517724-52b33b00-b86b-11e9-9a49-6ee9274b650d.png)

Here, I drop back to `v1.7.3` and I can get `terraform_docs` to work again:

![image](https://user-images.githubusercontent.com/295402/62517829-89895100-b86b-11e9-8446-a8a4be2b13e9.png)

Here, I bump to `v1.7.4` and the problem returns:

![image](https://user-images.githubusercontent.com/295402/62517887-a9b91000-b86b-11e9-9259-80ad227735e3.png)

I can repeat that with any version past `v1.7.3`. Here's `v1.9.0`:

![image](https://user-images.githubusercontent.com/295402/62518032-ee44ab80-b86b-11e9-8fc8-3f0825869293.png)

Unfortunately, I'm not sure where these hook scripts are installed, otherwise I'd try tracking down the failure myself. I'm happy to dig further myself if you can point me to where the hooks are installed so I can modify them for debugging?

**Comment by antonbabenko** [comment]
Closing this issue.

It was updated significantly since this issue has been opened.
