### ISSUE TITLE
Unclear on new terraform validate behaviour regarding variable checking

### ISSUE THREAD

**Issue by marcjay** [antonbabenko/pre-commit-terraform#61]
I can see that in the later versions of this project the two existing validate hooks have been reduced to one (`terraform_validate_with_variables.sh` and `terraform_validate_no_variables.sh` -> `terraform_validate.sh`)

The hooks file still suggests this single hook validates without checking variables: 
https://github.com/antonbabenko/pre-commit-terraform/blob/4bebeac734da116cc5fe535643252724321521a7/.pre-commit-hooks.yaml#L37-L39

But the script itself does not specify `-check-variables` and so seems to default to true, as per the docs:
https://www.terraform.io/docs/commands/validate.html#check-variables-true
https://github.com/antonbabenko/pre-commit-terraform/blob/4bebeac734da116cc5fe535643252724321521a7/terraform_validate.sh#L19

Please could you clarify the intended behaviour/reasoning behind dropping the option to not check variables? Would you accept a PR that re-introduced the option to skip the variable check without duplicating the script and creating a separate hook (e.g. allowing the hook to accept an argument to skip the checks).

Our project structure is such that some variables are only defined by external files, passed in via `-var-file` arguments to Terraform, and therefore do not validate successfully on their own

Many thanks

**Comment by antonbabenko** [comment]
Hi Marc,

The main reason is that `-check-variables` argument was removed in Terraform 0.12 and it fails if it is specified.

BTW [official documentation on `terraform validate`](https://www.terraform.io/docs/commands/validate.html#check-variables-true) is incorrect and should be updated.

If you are using the previous version of Terraform (<0.12) you can use one of the older releases of `pre-commit-terraform`.

If you have other questions, please don't hesitate to open an issue. 

Anton.

**Comment by marcjay** [comment]
Hi Anton,

Ah, many thanks, I was going off the documentation, which as you mention is incorrect - that explains the misunderstanding.

Thanks, will stay on 1.13.0 of `pre-commit-terraform` until our upgrade to 0.12 is complete

Cheers,

Marc
