### ISSUE TITLE
Update pre-commit-terraform to also use opentofu

### ISSUE THREAD

**Issue by willjw1** [antonbabenko/pre-commit-terraform#610]
We want to move from Terraform to OpenTofu

We do use pre-commit-terraform.  We'd like additional hooks put in place to support opentofu.  I'm not sure how many hooks completely support this at this point in time.  It does look like the existing hooks hardcode to use Terraform.

We are using:
1.8.6 version of pre-commit
v1.6.0-rc1 version of OpenTofu
I'm on darwin_amd64 14.2.1 Sonoma.

**Comment by MaxymVlasov** [comment]
Duplicated of #570

Write in the 570 issue if you'd like to implement it

**Comment by kvendingoldo** [comment]
Hello everyone. We started the fork and plan to adopt it to OpenTofu by the end of this week.
Welcome to contribute: https://github.com/tofuutils/pre-commit-opentofu
