### ISSUE TITLE
Enabling multiplatform support by moving to python

### ISSUE THREAD

**Issue by KyleOndy** [antonbabenko/pre-commit-terraform#62]
Is there any interest or appetite in porting the shell scripts to python to enable these pre-commit checks to work within environments where `bash` is not available, ex: windows?

**Comment by Aankhen** [comment]
I started working on that and then found that someone had already written [a script](https://github.com/marcuscaisey/.dotfiles/blob/master/scripts/terraform-docs12). See [marcuscaisey’s comment](https://github.com/segmentio/terraform-docs/issues/62#issuecomment-562557876) in segmentio/terraform-docs#62.

**Comment by KyleOndy** [comment]
Very cool! Thanks for the links to those references.

**Comment by Aankhen** [comment]
Not at all. I’m going to see if I can work on this and make it happen, since there’s more than just the conversion that’s written in Bash.

**Comment by Aankhen** [comment]
segmentio/terraform-docs#113 is now moving forward, so I’ll wait for that to land first.

**Comment by MaxymVlasov** [comment]
Python works extremely slowly than bash. Some years ago I wrote my own hooks in python 3 and then rewrite it to sh. Same logic - x10 times faster

If you do not use WSL in Windows, the better will be dockerize hooks, than rewrite it to python. In different systems installed different python versions - this will create many issues in the future.

**Comment by antonbabenko** [comment]
I agree, we won't prioritize support for multiplatform using Python. Bash or docker is better option.
