### ISSUE TITLE
Ability to use terraform_plan framework of checkov

### ISSUE THREAD

**Issue by michal-plebanski-ideals** [antonbabenko/pre-commit-terraform#643]
### What problem are you facing?

I would like to run terraform_checkov against a terraform plan, to be able to use a plan that correctly evaluates all variables. 

### How could pre-commit-terraform help solve your problem?

`hooks/terraform_checkov.sh` could be modified to optionally first run a terraform plan, generate a json file and then feed it into checkov for processing. 

It seems that today checkov is trying to take .tfvars into account but uses it's own parser and e.g. I have tfvars config file that is unparsable by checkov, even though it works normally with terraform.

**Comment by yermulnik** [comment]
It looks like that you'd like to use `pre-commit-terraform` to workaround an issue with `checkov`'s tfvars parsing — do I get you right?

**Comment by michal-plebanski-ideals** [comment]
Yes and no, it's true that framework "terraform" has a problem with tfvars parsing, but it's also true that terraform pre-commit-terraform has no support for checkov framework "terraform_plan". Using terraform_plan framework gives higher guarantee of what unit of work is evaluated in the check exactly - there is no need to rely on files or excludes and making sure they are correct and have the same scope as normal "terraform plan" execution.

**Comment by yermulnik** [comment]
Hmm, that sounds to me as a bit of overhead... Running `tf plan` may be a time-consuming operation (which might not be desired on e.g. specifically `pre-commit` stage as would run for every single `commit` action) and may require user to provide values for input vars interactively (or by means of cmdline plan customization options).

Implementation may require some effort as it will require to take into account all possible `tf plan` scenarios (success and failure, providing input vars via hook args and handling cases where TF would interactively ask for input of var values, so on).
While I understand your use case, I can't recall any other requests for the same recently, which may indicate low or exceptional demand 🤔

@MaxymVlasov What do you think overall about the request ans use acse per se?

Link to what @michal-plebanski-ideals refers to I guess: https://www.checkov.io/7.Scan%20Examples/Terraform%20Plan%20Scanning.html

ps: @michal-plebanski-ideals by the way, are you maybe up to try and contirbute given you're aware of the use case and is real user of the requested option?

**Comment by michal-plebanski-ideals** [comment]
@yermulnik Yes I can try to implement it, please let me know if you think it should be a separate hook or an extension to the existing terraform_checkov hook?

**Comment by yermulnik** [comment]
@michal-plebanski-ideals 👍🏻 
From my point of view (input from @MaxymVlasov is still missing 😿) ideally it would rely upon a hook configuration knob (like `--hook-config=--evaluate-tf-plan=true` and be implemented as part of `per_dir_hook_unique_part()` function (https://github.com/antonbabenko/pre-commit-terraform/blob/master/hooks/terraform_checkov.sh#L42)

**Comment by MaxymVlasov** [comment]
I think that it out of scope.
It should be part of IaC CI, like Atlantis, Terraform Cloud, Spacelift, GHA-action-which-runs-terraform-plan etc, not part of pre-commit. 

Also, there mostly impossible to guarantee that this functional will work for something more complex than vanilla terraform without workspaces (which could be managed by tools like `atmos` etc.)

For example, I have some extra tflint checks in Spacelift, precisely as a consequence of sentence above

```hcl
plugin "aws" {
    deep_check = true
```

**Comment by MaxymVlasov** [comment]
Also, let's imagine very simple structure with vanilla terraform on the default workspace:

```tree
some-app-module
└── main.tf
staging
├── main.tf
└── terraform.tfvars
prod
├── main.tf
└── terraform.tfvars
```

`some-app-module` has the logic needed, when `staging` and `prod` only includes it + provide some tfvars:

`staging/main.tf` and `prod/main.tf`:
```hcl
module "staging_app" {
  source = "../some-app-module"

  create_foo = var.create_foo
}
```

`staging/terraform.tfvars`:
```hcl
create_foo = true
```

`prod/terraform.tfvars`:
```hcl
create_foo = false
```

----


Now, imagine that you change something in `some-app-module/main.tf`

How pre-commit should know that it should go and run `t plan` for `staging/` and `prod/`?

**Comment by michal-plebanski-ideals** [comment]
Thanks for all the inputs, I agree that it should be part of CICD
