### ISSUE TITLE
Terraform trivy configuration excludes .trivyignore files, forcing repetitive ignore statements

### ISSUE THREAD

**Issue by ramongalate** [antonbabenko/pre-commit-terraform#646]
### Describe the bug

The code in the pre commit config excludes trivyignore files:
```
- id: terraform_trivy
  name: Terraform validate with trivy
  description: Static analysis of Terraform templates to spot potential security issues.
  require_serial: true
  entry: hooks/terraform_trivy.sh
  files: \.tf(vars)?$
  language: script
```

### How can we reproduce it?

Add a trivyignore file and try to use the hook.

### Environment information
```
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
```

**Comment by ramongalate** [comment]
currently this can be overriden with 
files: '\.tf(vars)?$|\.trivyignore$'
but it would be nice if it didn't exclude it as the standard

**Comment by yermulnik** [comment]
@ramongalate Would you please elaborate on what "_forcing repetitive ignore statements_" means and what makes you think `pre-commit-terraform` "_excludes trivyignore files_"?

**Comment by ramongalate** [comment]
@yermulnik when running a trivy command usually there are issues that give errors that you can ignore .

in cases where these issues happen several times, you can use a .trivyignore file to state the code to be ignore globally, instead of writing an ignore statement for every case.

since you specified to use only files that match `files: \.tf(vars)?$`, the global trivyignore file does not get included, like you would with `pass_filenames: false` or a more permissive regex.

**Comment by yermulnik** [comment]
> since you specified to use only files that match `files: \.tf(vars)?$`, the global trivyignore file does not get included

The `file:` parameter is not about which files are passed to trivy hook, but about changes to which files trigger trivy hook run (files location also infers the directory where `trivy` is run). If `.trivyignore` file, that you want `trivy` to take into account, is located in any of parent to TF-file(s) directory, then `trivy` obviously will not include it. In such case one option would be to configure hook to run an all files no matter which file(s) were chenged.

**Comment by nicolamarangoni** [comment]
I have the same issue:
`trivy config .` => .trivyignore is considered
`pre-commit run --all-files` => .trivyignore is NOT considered
@yermulnik what does it mean _"one option would be to configure hook to run an all files no matter which file(s) were chenged."_? I already sopecify `--all-files` in `pre-commit run`, what should I add to the hook config?
With terraform_tfsec I exclude checks using the args:
```
      - id: terraform_tfsec
        args:
          - "--args=-e aws-ssm-secret-use-customer-key,\
            aws-ecr-repository-customer-key,\
            aws-dynamodb-table-customer-key"
```
How does it work with `terraform_trivy`? I don't finy any hint in the documentation.

**Comment by MaxymVlasov** [comment]
If `.trivyignore` is just one file in repo root (or in one place in the repo) and should be used everywhere, try
```yaml
 - --args=--config-file=__GIT_WORKING_DIR__/.trivyignore
 ```

**Comment by nicolamarangoni** [comment]
@MaxymVlasov It works! Many thanks!
