### ISSUE TITLE
terraform_docs failing on complex types which contains "description" 

### ISSUE THREAD

**Issue by MaxymVlasov** [antonbabenko/pre-commit-terraform#65]
### How reproduce

Working code:

staged **README.md**
```txt
<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->

<!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
```
staged **vars.tf**
```terraform
variable "ingress_cidr_blocks" {
  description = "Bzzzzz"
  type = list(
    object({
      # description = string
      cidr_blocks = string
      from_port   = number
      to_port     = number
      protocol    = string
    })
  )

  default = [
    {
      description = "SG"
      cidr_blocks = "10.0.0.0/32"
      from_port   = 22
      to_port     = 22
      protocol    = "tcp"
    },
  ]
}

provider "aws" {
  region = "eu-west-1"
}
```

If uncomment ` # description = string` - terraform_docs failed:
```bash
Terraform docs...........................................................Failed
hookid: terraform_docs

2019/09/09 18:19:45 At 4:21: Unknown token: 4:21 IDENT string
```

### Root case

Error happens because awk rewrite this type to next construction:
```terraform
variable "ingress_cidr_blocks" {
  description = "Bzzzzz"
  type = "list("
      description = string
  default = [
    {
      description = "SG"
      cidr_blocks = "10.0.0.0/32"
      from_port   = 22
      to_port     = 22
      protocol    = "tcp"
    },
  ]
}
```

### Suggestion
"type" need be rewrite to "multiline", but I spend about 2 hours on it and not get excepted result.
I made crutch that fix error, but it will be good have full value, as in "default" block.

### Workaround

Just not specify `description` field in complex types.

**Comment by MaxymVlasov** [comment]
Hello @cytopia, 
Here is another bug-feature request for terraform_docs_awk.
Bug I propose fixing via patch, but it temporaty solution and not add to README full variable type

**Comment by cytopia** [comment]
@MaxymVlasov I was already playing around with this one, but it is kind of tough.

It could probably be much easier solved If I can assume that `terraform fmt` has **always** been applied beforehand, but not sure If that would be good.

**Comment by antonbabenko** [comment]
Well, if `terraform fmt` will make code in a way that `terraform_docs` always understand we can make it as a hard requirement and ask everyone to have something like this:

```
repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.19.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
```

**Comment by cytopia** [comment]
What should this type evaluate to?
```hcl
  type = list(
    object({
      # description = string
      cidr_blocks = string
      from_port   = number
      to_port     = number
      protocol    = string
    })
  )
```
Should it be just `list` or `list(object)` or `list(map(object))` or something else?

**Comment by antonbabenko** [comment]
This is not valid for 0.11, so it has to be treated as `type = list` which is valid in both 0.11 and 0.12.

**Comment by cytopia** [comment]
The valid types I found for 0.11 are:

* `list`
* `list(map(string))`
* `list(string)`

So the above case should eval to `list` then?

**Comment by cytopia** [comment]
@MaxymVlasov @antonbabenko I managed to create a fix without the requirement for `terraform fmt` beforehand. Can you guys give it a try:
```bash
docker run --rm \
  -v $(pwd):/data \
  cytopia/terraform-docs:0.6.0-release-0.11 \
  terraform-docs-replace-012 \
    --sort-inputs-by-required \
    --with-aggregate-type-defaults md README.md
```
If this works, I'll create a PR

**Comment by MaxymVlasov** [comment]
It works much better then my crutch. Thank you much @cytopia @antonbabenko
