### ISSUE TITLE
New Data Source: aws_ecr_lifecycle_policy_document

### ISSUE THREAD

**Issue by rwe-dtroup** [antonbabenko/pre-commit-terraform#669]
There has been a new datasource added, which is now causing the checks to fail

https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#5440-april--4-2024

```bash
Validation failed: .
╷
│ Error: Invalid data source
│ 
│   on data.tf line 1, in data "aws_ecr_lifecycle_policy_document" "default":
│    1: data "aws_ecr_lifecycle_policy_document" "default" {
│ 
│ The provider hashicorp/aws does not support data source
│ "aws_ecr_lifecycle_policy_document".
```

It would be useful for this to be supported.

Also, I can't see a way of ignoring the message until this is supported.

**Comment by yermulnik** [comment]
You're running TF provider for AWS version older than `5.44.0` and hence TF validation is failing. Run `terraform init -upgrade` and see whether this help.

NB: Running `terraform init -upgrade` would update `.terraform.lock.hcl` — take care of this according to your local policies for TFLock files.

**Comment by rwe-dtroup** [comment]
This is a fresh install of the provider

Terraform v1.7.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.47.0

Running the code itself is working fine

Unless I'm missing somewhere in the pre-commit config where the aws version is set?

**Comment by yermulnik** [comment]
Hmm... 🤔 Please post **full** console output.
Additionally please also follow [bug-report template](https://github.com/antonbabenko/pre-commit-terraform/issues/new?assignees=&labels=bug%2Carea%2Flocal_installation&projects=&template=bug_report_local_install.md) — this allows us to avoid guesstimating. Thanks.

**Comment by rwe-dtroup** [comment]
Thanks for the assist, seems it was one of the subfolders had the out of date provider.
