### ISSUE TITLE
Add changes made by terraform_fmt

### ISSUE THREAD

**Issue by alexppg** [antonbabenko/pre-commit-terraform#67]
Hi
It would be cool if terraform_fmt would add the changes done to the file to the commit. Right know, if you don't format the files, the process is:
- git add
- git commit 
- the hook modifies the unformatted file, formatting it
- git add 
- git commit

It may be:
- git add
- git commit 
- the hook modifies the unformatted file, formatting it, and adds it to the commit

I remember this happening automatically with this hook a couple of months ago, but I can't reproduce it, so maybe I'm just wrong.

PD: Thanks for your work, it's awesome.

**Comment by lewandom** [comment]
https://github.com/pre-commit/pre-commit/issues/532

**Comment by antonbabenko** [comment]
¡Hola Àlex!

As @lewandom said... Less magic = fewer surprises when something is committed unintentionally :)

PS: You are welcome!

**Comment by alexppg** [comment]
I see. Thanks!
