### ISSUE TITLE
Terragrunt validate-inputs hook?

### ISSUE THREAD

**Issue by jmreicha** [antonbabenko/pre-commit-terraform#675]
### What problem are you facing?

It looks like Terragrunt supports the validate-inputs subcommand. This would be helpful to run as a pre-commit hook to catch potential misconfigurations before runtime. It can also catch unused inputs with an additional flag that can help clean up configs.

https://terragrunt.gruntwork.io/docs/reference/cli-options/#validate-inputs

### How could pre-commit-terraform help solve your problem?

It looks like some time and effort can be saved by catching these config issues early in the development process.

**Comment by yermulnik** [comment]
@jmreicha Thanks for raising this.
Any chance you would like to try and contribute by e.g. taking https://github.com/antonbabenko/pre-commit-terraform/blob/master/hooks/terragrunt_validate.sh as template?

**Comment by jmreicha** [comment]
Hey yeah, I would be interested. I will start with the script you linked and go from there and see what I can come up with!

**Comment by MaxymVlasov** [comment]
Yeah, it will be a nice addition, will wait to your PR.

Btw, here some instructions, which you can find helpful https://github.com/antonbabenko/pre-commit-terraform/blob/master/.github/CONTRIBUTING.md#add-new-hook

**Comment by jmreicha** [comment]
Have a look https://github.com/antonbabenko/pre-commit-terraform/pull/677

It dose appear to require auth to the provider I was testing, not sure if there are any tricks for getting around it but it does work.

**Comment by yermulnik** [comment]
> It does appear to require auth to the provider I was testing with, not sure if there are any tricks for getting around it but it does work.

Maybe just add this caveat to this new hook description in README?

**Comment by jmreicha** [comment]
Yeah that works for me. The validate hook behaves the same way so I’m good with that.
