### ISSUE TITLE
`terraform_docs` hook broken in `v1.92.2`

### ISSUE THREAD

**Issue by Shr3ps** [antonbabenko/pre-commit-terraform#699]
### Describe the bug

Using the latest version of the hook (v1.92.2), pre-commit is always in "PASSED" state even if we change variables, outputs or versions constrains.

### How can we reproduce it?

```bash
vim versions.tf
sed -i 's/version = "~> 3.80"/version = "~> 3.86"/g' versions.tf
pre-commit run -a

Terraform fmt...........................................................................Passed
Terraform docs..........................................................................Passed
```

It should failed and update README.md file.

### Environment information

* OS:  

OS: Win11 with Ubuntu 20.04 on WSL2
OS: Ubuntu 20.04

* Docker image tag/git commit:  v1.92.2

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```yaml
  25   │   - repo: https://github.com/antonbabenko/pre-commit-terraform.git
  26   │     rev: v1.92.2
  27   │     hooks:
  28   │       - id: terraform_fmt
  29   │         stages: [pre-commit]
  30   │       - id: terraform_docs
  31   │         stages: [pre-commit]
  32   │         args:
  33   │           - --args=--config=.config/terraform-docs.yml
```

</details>

**Comment by Shr3ps** [comment]
(everything is working as expected with v1.92.1)

**Comment by yermulnik** [comment]
Might probably be related to https://github.com/antonbabenko/pre-commit-terraform/pull/698 🤔 

@Shr3ps Would you please also share contents of the `.config/terraform-docs.yml` file?

**Comment by Shr3ps** [comment]
> Might probably be related to #698 🤔
> 
> @Shr3ps Would you please also share contents of the `.config/terraform-docs.yml` file?

Yep, here you go: 

```yaml
---
# This file is automatically maintained within this module repository -- DO NOT EDIT
formatter: "markdown"

settings:
  anchor: false
  lockfile: false

output:
  file: "README.md"

sections:
  hide: [requirements]

content: |-
  ## Global versioning rule for Claranet Azure modules

  | Module version | Terraform version | AzureRM version |
  | -------------- | ----------------- | --------------- |
  | >= 7.x.x       | 1.3.x             | >= 3.0          |
  | >= 6.x.x       | 1.x               | >= 3.0          |
  | >= 5.x.x       | 0.15.x            | >= 2.0          |
  | >= 4.x.x       | 0.13.x / 0.14.x   | >= 2.0          |
  | >= 3.x.x       | 0.12.x            | >= 2.0          |
  | >= 2.x.x       | 0.12.x            | < 2.0           |
  | <  2.x.x       | 0.11.x            | < 2.0           |

  ## Contributing

  If you want to contribute to this repository, feel free to use our [pre-commit](https://pre-commit.com/) git hook configuration
  which will help you automatically update and format some files for you by enforcing our Terraform code module best-practices.

  More details are available in the [CONTRIBUTING.md](./CONTRIBUTING.md#pull-request-process) file.

  ## Usage

  This module is optimized to work with the [Claranet terraform-wrapper](https://github.com/claranet/terraform-wrapper) tool
  which set some terraform variables in the environment needed by this module.
  More details about variables set by the `terraform-wrapper` available in the [documentation](https://github.com/claranet/terraform-wrapper#environment).

  ```hcl
  {{ include "examples/main/modules.tf" }}
  ```

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
...
```

**Comment by yermulnik** [comment]
@Shr3ps Thank you.

@MaxymVlasov Need your brain here 🤷🏻

**Comment by MaxymVlasov** [comment]
As you used wrong bug template, @Shr3ps please provide info about environment.

https://github.com/antonbabenko/pre-commit-terraform/blob/f809e53ddfcab9fbeb0d58adaf0c44f5dfc8e706/.github/ISSUE_TEMPLATE/bug_report_local_install.md#L74-L101

Because currently, I can't reproduce this issue.

But I found a minor issue that if output.file specified, warning always shown 
![image](https://github.com/user-attachments/assets/55ff7ac7-2d82-4854-a867-9b06d956c3f0)

**Comment by Shr3ps** [comment]
Hello,

some steps to reproduce my issue:

```bash
$ git clone https://github.com/claranet/terraform-azurerm-rg/
$ cd terraform-azurerm-rg 
$ pre-commit install 
$ sed -i 's/>= 1.32/>= 1.33/g' versions.tf     
$ sed -i 's/Resource group name/Resource group name./g' outputs.tf
$ git add .
$ pre-commit run
$ git commit -m 'chore: test pre-commit'
```

the bug is that pre-commit outputs:
```
Terraform fmt...........................................................................Passed
Terraform docs..........................................................................Passed
Terraform validate......................................................................Passed
Terraform validate with tflint..........................................................Passed
```

but should fail instead because of the changes done on .tf files.


### Environment information

* `$ uname -a`
Linux FR-LAP822653786 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

* Tools availability and versions:
```bash
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
pre-commit 3.7.0
OpenTofu v1.8.1
Terraform v1.5.3
python SKIPPED
Python 3.10.12
checkov SKIPPED
infracost SKIPPED
terraform-docs version v0.18.0 228c7a7 linux/amd64
terragrunt SKIPPED
terrascan version: v1.1.0
TFLint version 0.44.1
+ ruleset.terraform (0.2.2-bundled)
tfsec v1.28.1
trivy Version: 0.54.1
tfupdate SKIPPED
hcledit SKIPPED
```

* `.pre-commit-config.yaml`:
https://github.com/claranet/terraform-azurerm-rg/blob/master/.pre-commit-config.yaml

**Comment by MaxymVlasov** [comment]
Default markers:
![Screenshot from 2024-08-27 20-05-11](https://github.com/user-attachments/assets/de4d8bc0-b9b3-4bbf-bfca-10aa20c46b29)
Your markers:
![Screenshot from 2024-08-27 20-07-01](https://github.com/user-attachments/assets/9c2eb896-cc52-4da0-87e1-a9cea5205d66)

Documentation about that:
![Screenshot from 2024-08-27 20-05-45](https://github.com/user-attachments/assets/8ed3d841-f43b-47ba-b16d-1b376007a403)


So you just need to set
```yaml
      - id: terraform_docs
        args:
          - --args=--config=.config/terraform-docs.yml
          - --hook-config=--use-standard-markers=true
```
to work as expected.

I am not sure why it was able to work before 1.92.2, but that wasn't expected behavior.

We could release a new minor version which will include force change of markers to TF_DOCS default makers (they were introduced a few years later than in this repo, that's why they different), but that will not be a bug fix :)

**Comment by MaxymVlasov** [comment]
Also, check https://github.com/antonbabenko/pre-commit-terraform/pull/701

**Comment by Shr3ps** [comment]
Thanks @MaxymVlasov , I can confirm adding the param `- --hook-config=--use-standard-markers=true` fixes the issue.

**Comment by MaxymVlasov** [comment]
@Shr3ps v1.93.0 should work without `- --hook-config=--use-standard-markers=true`
