### ISSUE TITLE
Add hook to generate documentation using terraform-docs

### ISSUE THREAD

**Issue by antonbabenko** [antonbabenko/pre-commit-terraform#7]
Remaining to-do:
- [x] Allow to specify filename to update (default, `README.md`) Estimate: 1 hour. [Code](https://github.com/antonbabenko/pre-commit-terraform/blob/master/terraform_docs.sh#L113) Done by #245
- [ ] Check for changes not only in `tf` files, probably (but also in `README.md`)

There is this great blog post by @davidbegin:
- http://www.davidbegin.com/using-terraform-docs-to-automate-keeping-your-terraform-modules-documenting/

**Comment by MaxymVlasov** [comment]
Blog post are not accessible now, no cache or archive exist.


Second checkbox totally is #256. 


So I close this issue as less informative than duplicate in #256 :)
