### ISSUE TITLE
TFLint --deep argument

### ISSUE THREAD

**Issue by benmontour-wf** [antonbabenko/pre-commit-terraform#71]
I'd like to see the tflint pre-commit script have --deep be an optional argument rather than the default. I believe --deep only works with AWS and causes issues if you attempt to run it for GCP or Azure infrastructure.

**Comment by antonbabenko** [comment]
[v1.21.0](https://github.com/antonbabenko/pre-commit-terraform/releases/v1.21.0) of this module has been just released.

It is now possible to specify it like this:
```
    - id: terraform_tflint
      args: ['--deep']
```
