### ISSUE TITLE
terraform docs in conatiner outdated

### ISSUE THREAD

**Issue by jwhitcraft** [antonbabenko/pre-commit-terraform#724]
### Describe the bug

When running terraform-docs locally we are using 0.19.0 which has this "[fix](https://github.com/terraform-docs/terraform-docs/commit/78e94da7864d47732bbd941fe5c4e081ccd77e74)"

But when running the the container it's only v0.18.0

![image](https://github.com/user-attachments/assets/5ae792b4-39cb-48b0-b223-216b3de27ccd)

### How can we reproduce it?

Update a read-me locally that will contain new lines, they run the docker container over it and see notice it changes

**Comment by MaxymVlasov** [comment]
Pre-built docker images contained latest version of tools available during it buid time, and never change again.
If you want to use latest builds - use `nightly` tag - https://github.com/antonbabenko/pre-commit-terraform/pkgs/container/pre-commit-terraform/291188741?tag=nightly

Or you can build your own image with needed versions, for this - checkout `Docker` section in https://github.com/antonbabenko/pre-commit-terraform?tab=readme-ov-file#1-install-dependencies

**Comment by MaxymVlasov** [comment]
Ah yes. To  prevent accidental update to new version w/o your attention - use image digest
![image](https://github.com/user-attachments/assets/e6bb0ecf-f321-4ced-b131-6516ed4389db)

**Comment by diegolagospagopa** [comment]
> Ah yes. To prevent accidental update to new version w/o your attention - use image digest ![image](https://private-user-images.githubusercontent.com/11096782/380847632-e6bb0ecf-f321-4ced-b131-6516ed4389db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTg4OTEsIm5iZiI6MTczMDE5ODU5MSwicGF0aCI6Ii8xMTA5Njc4Mi8zODA4NDc2MzItZTZiYjBlY2YtZjMyMS00Y2VkLWIxMzEtNjUxNmVkNDM4OWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDEwNDMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYjA4YTJmMjE1OWMyYmQ2M2IwMzZhMDE5OGYzNTYyZDU2ZDA0MjViMGNkMGM2NDI2OTJlMDIzNTQxMjQwMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pJU0xhwb11YFa1vImhKEB-YVsB8Bl9gXMixf2knl-n4)

We use hashes, the problem is related to our workflow where you launch pre-commit locally that has terraform-docs v0.19.0 (and I can't change it) and the version that is currently inside the docker image v0.18.0.

As a result, I create a type of doc locally that is not consistent with the one generated by our CI.

For this reason I ask the kindness of generating a new image that upgrades terraform-docs to version 0.19.0

**Comment by MaxymVlasov** [comment]
Feel free to send PR which will introduce a GH workflow which will generate and tag, idk, `<hook-version>_<tool>-<version>_<tool2>-<version>_<tool3>-<version>...`? for last 10 hook versions?

**Comment by MaxymVlasov** [comment]
1.96.2 should contain terraform-docs 0.19.0

**Comment by jwhitcraft** [comment]
> 1.96.2 should contain terraform-docs 0.19.0

no container exist for 1.96.2: https://github.com/antonbabenko/pre-commit-terraform/pkgs/container/pre-commit-terraform

**Comment by MaxymVlasov** [comment]
@jwhitcraft thank you for notifying, fixed.
https://github.com/antonbabenko/pre-commit-terraform/pkgs/container/pre-commit-terraform/300563841?tag=v1.96.2

**Comment by diegolagospagopa** [comment]
Perfect, it works 😄
