### ISSUE TITLE
Add support for segmentio/terraform-docs

### ISSUE THREAD

**Issue by diegombeltran** [antonbabenko/pre-commit-terraform#81]
Hello,

Now that this [issue](https://github.com/segmentio/terraform-docs/issues/62#event-2901921608) appears to be resolved, maybe we can run terraform-docs withouth the hacky awk workaround :)

**Comment by grzegorzlisowski** [comment]
I'm testing this on my fork for few days, but it requires terraform-docs built from master branch.

**Comment by khos2ow** [comment]
FYI, I'm the in the process of cutting a RC release of terraform-docs, in the following days.

**Comment by james-gonzalez** [comment]
RC has been released :)

https://github.com/segmentio/terraform-docs/releases/tag/v0.8.0-rc.1

**Comment by tbugfinder** [comment]
terraform-docs v0.8.0 has been released.

**Comment by konstantin-recurly** [comment]
It looks like, with the latest release the terraform-docs has been implemented.

**Comment by antonbabenko** [comment]
Correct, please use [v1.23.0](https://github.com/antonbabenko/pre-commit-terraform/releases/v1.23.0).

@khos2ow, thanks for great work on terraform-docs!

**Comment by james-gonzalez** [comment]
Thanks @antonbabenko !
