### ISSUE TITLE
Support running executables via docker

### ISSUE THREAD

**Issue by abohne** [antonbabenko/pre-commit-terraform#89]
Would it be possible to support running the docker versions of the executables?

i.e. 
`terraform` -> `docker run -i -t hashicorp/terraform:light`
`tflint` -> `docker run --rm -v $(pwd):/data -t wata727/tflint`

**Comment by antonbabenko** [comment]
Hi Andy,

In theory, everything is possible:

```
alias terraform="docker run -i -t hashicorp/terraform:light"
```

The question to solve is how can we make it work for the majority of people without duplicating code - with docker and without docker?

**Comment by MaxymVlasov** [comment]
Done, Look on [`Docker` section](https://github.com/antonbabenko/pre-commit-terraform#1-install-dependencies).
