### ISSUE TITLE
#93 resolution incorrect

### ISSUE THREAD

**Issue by ctodd-cb** [antonbabenko/pre-commit-terraform#97]
I'm hitting this issue today and can't validate the solution in #93. I am attempting to pass multiple arguments. When I set an additional arg, it ignores the previous. 

I've used the following syntax:
```
    - id: terraform_tflint
      args:
        - 'args=--disable-rule=terraform_deprecated_interpolation'
        - 'args=--disable-rule=aws_elasticache_cluster_previous_type'
```
as well as this one:
```
    - id: terraform_tflint
      args: ['args=--disable-rule=terraform_deprecated_interpolation', 'args=--disable-rule=aws_elasticache_cluster_previous_type']
```

----

This appears to be true based on the case statement here:
https://github.com/antonbabenko/pre-commit-terraform/blob/master/terraform_tflint.sh#L13
It overloads the `args` variable each loop rather than appending.

However, the solution below will work as the string is the complete list of arguments to pass. The output also matches the expected output from `tflint --disable-rule=terraform_deprecated_interpolation --disable-rule=aws_elasticache_cluster_previous_type`
```
    - id: terraform_tflint
      args: [--args=--disable-rule=terraform_deprecated_interpolation --disable-rule=aws_elasticache_cluster_previous_type]
```

Solution preference? Should the case statement handle that like a string (update documentation to reflect this syntax) or like an array (PR to `terraform_tflint.sh`)? 

TIA!

**Comment by ouranos** [comment]
I had the same issue and it took me a while to figure out what was going on.

I wanted to enable all the new rules and ended up doing this:
```
    - id: terraform_tflint
      args: 
        - >
            --args=--enable-rule=terraform_unused_declarations
            --enable-rule=terraform_comment_syntax
            --enable-rule=terraform_documented_outputs
            --enable-rule=terraform_documented_variables
            --enable-rule=terraform_typed_variables
            --enable-rule=terraform_required_version
            --enable-rule=terraform_required_providers
            --enable-rule=terraform_naming_convention
```
That syntax feels a bit weird so it'd probably be better to patch the script to work as per the documentation?

**Comment by ctodd-cb** [comment]
It appears the originally observed behavior reverted in [`v1.33.0`](https://github.com/antonbabenko/pre-commit-terraform/commit/774c63e772f1d933a066ae59ca74e7137f1d982a#) as it now [appends to the ARGS list](https://github.com/antonbabenko/pre-commit-terraform/commit/774c63e772f1d933a066ae59ca74e7137f1d982a#diff-ecd725adc8a5294ee7eda14bb3f8b340fef9c66c2c79d2c96f3b2025af5a2a8bR38) rather than overwriting it. 

Expected format is as follows:
```
    - id: terraform_tflint
      args:
        - 'args=--disable-rule=terraform_deprecated_interpolation'
        - 'args=--disable-rule=aws_elasticache_cluster_previous_type'
```
