### ISSUE TITLE
releases aren't really releases

### ISSUE THREAD

**Issue by grimm26** [antonbabenko/pre-commit-terraform#99]
For some reason I cannot list releases on this repo.  API calls like https://docs.github.com/en/rest/reference/repos#get-the-latest-release fail.  I can list tags, but not releases.  Maybe they are not really releases somehow?  I'm writing something to make sure I keep the latest release in my yaml for this :)

**Comment by antonbabenko** [comment]
I think you are right, the latest release is not actually marked as `latest` according to GitHub.

I have opened an issue https://github.com/pnikosis/semtag/issues/11 in [semtag repository](https://github.com/pnikosis/semtag) to track what can be done there.

**Comment by 1efty** [comment]
@antonbabenko I'm building a replacement using go https://github.com/1efty/semtag 

It's not feature complete yet, but hoping to get there shortly. Maybe this request could be incorporated into v1.

**Comment by antonbabenko** [comment]
@1efty I don't think I am eager to replace working solution with existing semtag to anything else in the near future.

**Comment by MaxymVlasov** [comment]
@grimm26 I think you just need to use `pre-commit autoupdate` command, not try to write your own wrappers

**Comment by grimm26** [comment]
@MaxymVlasov yes i'm doing that now
